### PR TITLE
Add pending WorkflowRunStatus

### PR DESCRIPTION
**Pull request by beliakov-mb**
Resolves [#2656](https://github.com/octokit/octokit.net/issues/2656)

----

### Before the change?
WorkflowRunStatus enum does not contain "pending" value.

* 

### After the change?
WorkflowRunStatus enum contains "pending" value.

* 

### Other information

* 

----

### Pull request checklist
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been reviewed and added / updated if needed (for bug fixes / features)
- [ ] Added the appropriate label for the given change

### Does this introduce a breaking change?

Please see our docs on [breaking changes](https://github.com/octokit/.github/blob/master/community/breaking_changes.md) to help!

- [ ] Yes (Please add the `Type: Breaking change` label)
- [x] No

If `Yes`, what's the impact:  

* N/A

### Pull request type

 
 

Please add the corresponding label for change this PR introduces:
- Bugfix: `Type: Bug`
- Feature/model/API additions: `Type: Feature`
- Updates to docs or samples: `Type: Documentation`
- Dependencies/code cleanup: `Type: Maintenance`

----

### CODE REVIEW

**Comment by kfcampbell** [comment]
@beliakov-mb do you mind pointing me towards the API documentation where this is defined? I see that in the [List workflow runs for a workflow API](https://docs.github.com/en/rest/actions/workflow-runs?apiVersion=2022-11-28#list-workflow-runs-for-a-workflow), potential statuses are defined as: 

> Can be one of: completed, action_required, cancelled, failure, neutral, skipped, stale, success, timed_out, in_progress, queued, requested, waiting

Does "pending" correspond to "waiting"? Maybe "requested"?

**Comment by beliakov-mb** [comment]
Indeed, this condition is not in the documentation, but I get it from the github rest api, and catch the error (look at the attached issue)

I'll try to investigate how to reproduce such a state.

**Comment by kfcampbell** [comment]
Oh gosh, that's a hassle. I would definitely be curious how to trigger it!

**Comment by nickfloyd** [comment]
@beliakov-mb Thanks for catching this and getting an update in here... I'm going to reach out to our docs team to make sure this get's updated. ❤️

**Review by nickfloyd — APPROVED** [review]

**Pull request merged**
