### PR TITLE
Add link to corefx coding conventions

### PR DESCRIPTION
**Pull request by M-Zuber**
I am working in gitter to understand what to put in a seperate file of custom coding conventions for the project.
But this should be here either way

### CODE REVIEW

**Comment by shiftkey** [comment]
Possibly related - should we reference the CodeFormatter project added in #807?

If so, I need to update [this repo](https://github.com/shiftkey/codeformatter) to reflect it's intent...

**Comment by M-Zuber** [comment]
Oh yes,  that should definitely be mentioned. 
The way I am leaning is too link from contributing. md to a CustomCodingConventions.md file.

**Comment by M-Zuber** [comment]
But that will have to wait until I am not on my phone. 
(also editing a comment)

**Comment by shiftkey** [comment]
@M-Zuber this feels like it could be part of the documentation we're putting together in #948. Do you agree?

**Comment by M-Zuber** [comment]
This specific pull request or the new file? 
New file yes,  this not (as I see it) 

As a side note: responding through email takes an awful long time to show up...

**Comment by shiftkey** [comment]
Let's take this in and then expand on it in some documentation.

Thanks @M-Zuber!

**Pull request merged**
