### PR TITLE
Correctly deserialize CollaboratorPermissionResponse

### LINKED ISSUE #2681: Octokit.net v5 doesn't deserialize user permissions response correctly
Based on https://github.com/octokit/octokit.net/blob/7d01bad2971b751f3b6736c57c9349d318a37293/Octokit/Clients/RepoCollaboratorsClient.cs#L242, a `CollaboratorPermissionResponse` needs to have a `Collaborator` since you're deserializing the response, but this, in practice, is `null because the [response schema](https://docs.github.com/en/rest/collaborators/collaborators?apiVersion=2022-11-28#get-repository-permissions-for-a-user) returns "user" and there's no obvious mapping between "user" and "collaborator".

/cc @JimSuplizio

### PR DESCRIPTION
**Pull request by heaths**
Fixes #2681

### CODE REVIEW

**Comment by nickfloyd** [comment]
Hey @heaths, I am taking a look at this now... thank you for jumping on this so quickly. I missed it in my review the other day; appologies for that oversight! ❤️

**Review by nickfloyd — APPROVED** [review]
Looks good.  Thanks for the going the extra mile with tests and a fixture ❤️

**Comment by heaths** [comment]
Might we see a 5.1.1 in the near-ish future? For now we used the legacy `PCollaboratorPermissionResponse.Permission` string property but seems the new, more granular permission model gives us the better access we need than checking for "admin" or "write" - now we can just test if the nested "push" is true.

/cc @JimSuplizio who is working on incorporating this new version into our bot.

**Pull request merged**
