### PR TITLE
setting test credentials - now eleventy billion % easier

### PR DESCRIPTION
**Pull request by shiftkey**
I found myself on a fresh VM and realised I hadn't set up the test variables for Octokit.

So I scripted it out in some rough PowerShell (indicating which are optional parameters for tests which are specific to features not everyone runs - like private repositories or application tests):

```
> .\script\configure-integration-tests.ps1
BIG FREAKING WARNING!!!!!
You should use a test account when running the Octokit integration tests!


Set the account name to use for the integration tests (required): shiftkey-tester
Set the account password to use for the integration tests (optional):
Set the OAuth token to use for the integration tests (required): {token}
Do you have private repositories associated with your test account? Press Y to set this, otherwise we'll skip it: Y
Set the organization name to use for the integration tests (optional): shiftkey-tester-org-blah-blah
Set the application ClientID to use for the integration tests (optional): {token}
Set the application Secret to use for the integration tests (optional): {token}
> 
```

When you run the same script again, it'll display your existing values and ask if you want to update them:

```
> .\script\configure-integration-tests.ps1
BIG FREAKING WARNING!!!!!
You should use a test account when running the Octokit integration tests!


shiftkey-tester found as the configured account name
Want to change this? Press Y, otherwise we'll move on:
Set the account password to use for the integration tests (optional):
{token} found as the configured OAuth token
Want to change this? Press Y, otherwise we'll move on: 
...
```

Let me know if there's any way to make this experience a bit more friendly.

- [x] let me actually review this before someone eagerly merges it
- [x] set for your current session as well, so you don't go wondering why things didn't update
- [x] can run all the integration tests again
- [x] opt-out of basic authentication tests (it's optional)
- [x] correctly differentiate where tests require Basic Auth
- [x] open issues for now-muted tests
- [x] link to issues in code

### CODE REVIEW

**Comment by M-Zuber** [comment]
This is already a big step up.
When I first tried contributing I had trouble setting things up as I had never used environment variables before.
Having even a simple script like this would have been a major help

**Comment by alfhenrik** [comment]
LGTM :+1:

**Comment by M-Zuber** [comment]
Looks great to me. :+1:
thank you for your hard work and apologies if i came across snappy above

**Comment by Haacked** [comment]
Nice! Maybe a next step would be to have the script use Octokit.net to help you create the test accounts if you don't have them!

_Nerd snipe_

**Comment by M-Zuber** [comment]
Meta all the things!!!

**Comment by shiftkey** [comment]
> Nice! Maybe a next step would be to have the script use Octokit.net to help you create the test accounts if you don't have them!

Not possible through the API :(

**Comment by Haacked** [comment]
> Not possible through the API :(



Darn.

**Comment by alfhenrik** [comment]
image

:sob:

**Comment by Haacked** [comment]
The potential for abuse is high for github.com. We get enough spammer accounts without making it even easier to automate. :)

**Comment by alfhenrik** [comment]
Yep, can understand that :grinning:

**Comment by shiftkey** [comment]
Tweaking the output a bit to make things clearer:

```
> .\script\configure-integration-tests.ps1

BIG FREAKING WARNING!!!!!
You should use a test account when running the Octokit integration tests!


shiftkey-tester found as the configured account name
Want to change this? Press Y, otherwise we'll move on:

Set the account password to use for the integration tests (optional):

XXX found as the configured OAuth token
Want to change this? Press Y, otherwise we'll move on:

Do you have private repositories associated with your test account? Press Y to set this, otherwise we'll skip it:

shiftkey-tester-org-blah-blah found as the configured organization name
Want to change this? Press Y, otherwise we'll move on:
Want to remove this optional value, press Y:

XXX found as the configured application ClientID
Want to change this? Press Y, otherwise we'll move on:
Want to remove this optional value, press Y:

XXX found as the configured application Secret
Want to change this? Press Y, otherwise we'll move on:
Want to remove this optional value, press Y:
```

**Comment by shiftkey** [comment]
:apple:

**Comment by Haacked** [comment]
:sparkles: Really nicely done @shiftkey!

thumbs-up-batman

**Pull request merged**
