### PR TITLE
Json serialization for Unicode

### PR DESCRIPTION
**Pull request by naveensrinivasan**
This will fix the Unicode Json serialization bug https://github.com/octokit/octokit.net/issues/967.

When I was looking at the code I realized there was already a fix with a PR https://github.com/facebook-csharp-sdk/simple-json/pull/66 .Reused the same code for this fix.

### CODE REVIEW

**Comment by ferventcoder** [comment]
Sweet. :)

**Comment by Haacked** [comment]
I'm hesitant to take this because `SimpleJson.cs` is a dependency we pull in from NuGet. Have you tried the latest version to see if it already has a fix?

If not, could you submit a PR upstream to https://github.com/facebook-csharp-sdk/simple-json?

I worry that the next time we upgrade, we'll break this. At least the unit test will catch it though. :smile:

**Comment by naveensrinivasan** [comment]
@Haacked  I looked for that first before making the change. https://github.com/facebook-csharp-sdk/simple-json hasn't been updated in the last 20 months. There is already a PR with this fix for the main repo which is still pending from April. That's the reason for making a change in this repo.

I understand your concerns. What do you want to do?

**Comment by khellang** [comment]
Ping @prabirshrestha and ask what he's been up to? :wink:

**Comment by Haacked** [comment]
Ok, as long as the PR is upstream, I'll take this one.

**Pull request merged**
