### PR TITLE
[FEAT] Self-hosted runners and Self-hosted runner groups APIs

### LINKED ISSUE #2692: [FEAT]: Self-Hosted Runners and Runner Groups API Support
### Describe the need

I'd like to contribute the following set of API's to the project [self-hosted runners](https://docs.github.com/en/rest/actions/self-hosted-runners?apiVersion=2022-11-28) and [self-hosted runner groups](https://docs.github.com/en/enterprise-cloud@latest/rest/actions/self-hosted-runner-groups?apiVersion=2022-11-28). I work at GitHub on the Field Engineering team (under Customer Success), and we rely on this project, and are having to call the GitHub API manually to interact with self-hosted runners. I'd like to contribute back to this project and add support for these missing API's so we can fully adopt Octokit, and remove our custom clients that we've written to communicate with the GitHub self-hosted runner API's.

### SDK Version

_No response_

### API Version

_No response_

### Relevant log output

_No response_

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### PR DESCRIPTION
**Pull request by lineville**
Resolves #2692 by implementing support for the following API's

### Self-Hosted Runners
- [x] List self-hosted runners for an enterprise
- [x] List self-hosted runners for an organization
- [x] List self-hosted runners for a repository
- [x] List self-hosted runners for a group in an enterprise
- [x] List self-hosted runners for a group in an organization
- [x] List self-hosted runner applications for an enterprise
- [x] List self-hosted runner applications for an organization
- [x] List self-hosted runner applications for a repository
- [x] Delete a self-hosted runner for an enterprise
- [x] Delete a self-hosted runner for an organization
- [x] Delete a self-hosted runner for a repository
- [x] Create a self-hosted runner registration token for an enterprise
- [x] Create a self-hosted runner registration token for an organization
- [x] Create a self-hosted runner registration token for a repository

### Self-Hosted Runner Groups
- [x] List self-hosted runner groups for an enterprise
- [x] List self-hosted runner groups for an organization
- [x] List organization access to a self-hosted runner group in an enterprise
- [x] List repository access to a self-hosted runner group in an organization

----

### Before the change?

* The `ActionsSelfHostedRunnersClient` and `ActionsSelfHostedRunnerGroupsClient` we're empty and not implemented

### After the change?

* The `ActionsSelfHostedRunnersClient` and `ActionsSelfHostedRunnerGroupsClient` have been implemented (non-exhaustively) to include several of the available API's (listed above)

### Other information

* Models that we're added include `Runner`, `RunnerResponse`, `RunnerApplication` and `RunnerApplicationResponse`
* There are many APIs under the `Self-Hosted Runner` and `Self-Hosted Runner Groups` that are left unimplemented after this PR

----

### Pull request checklist
- [x] Tests for the changes have been added (for bug fixes / features)
- [x] Docs have been reviewed and added / updated if needed (for bug fixes / features)
- [ ] Added the appropriate label for the given change

☝️ Unable to add labels to the PR 😕 but should be tagged with feature

### Does this introduce a breaking change?

Please see our docs on [breaking changes](https://github.com/octokit/.github/blob/master/community/breaking_changes.md) to help!

- [ ] Yes (Please add the `Type: Breaking change` label)
- [x] No

If `Yes`, what's the impact:  

* N/A

### Pull request type

 
 

Please add the corresponding label for change this PR introduces:
- Bugfix: `Type: Bug`
- Feature/model/API additions: `Type: Feature`
- Updates to docs or samples: `Type: Documentation`
- Dependencies/code cleanup: `Type: Maintenance`

----

### CODE REVIEW

**Comment by kfcampbell** [comment]
@lineville is this still something you're interested in getting in?

**Comment by lineville** [comment]
> @lineville is this still something you're interested in getting in?

Yes, I'd love to get this in. I have been working on adding some integration tests. I have been facing some issues with authenticating given that some of the tests need to access an enterprise etc. Unit tests and Convention tests and docs are done ✅, was just trying to finish up some integration tests, or at least validate somehow it's functional end to end before opening this PR up for review.

@kfcampbell If you have any ideas about running integration tests against an enterprise, or any details you might have about how the existing integration tests are run locally or in CI would be super helpful 🙇

**Comment by kfcampbell** [comment]
As far as I'm aware, [this](https://github.com/octokit/octokit.net/blob/main/build.sh) the only script used in our automated checks, which runs unit tests but not any integration tests. I think we'd be working from scratch with enterprise integration testing.

**Comment by lineville** [comment]
@kfcampbell Thanks! I won't worry too much about having exhaustive integration tests then, given that it's not run in CI anyways. I'll open this PR up for review shortly!

**Comment by kfcampbell** [comment]
@lineville release cadence is ad-hoc depending on PRs that have been merged. When this goes in, we can cut a release shortly thereafter.

**Comment by lineville** [comment]
@kfcampbell Just bumping this 😄, any ideas when we could expect this to be merged and released? Is there anything from my end that might be holding this up?

**Review by nickfloyd — APPROVED** [review]
This looks great!  Thank you for the changes ❤️

**Pull request merged**
