### PR TITLE
Added UpdatedAt property to Milestone.

### PR DESCRIPTION
**Pull request by shaggygi**
Added UpdatedAt property to Milestone.  It seems like this would not be null, but added similar to ClosedAt property just in case.  This is also a breaking change to Milestone constructor.

### CODE REVIEW

**Comment by ryangribble** [comment]
Thanks @shaggygi 


LGTM

**Comment by ryangribble** [comment]
TravisCI is having some sort of issue at the moment, I'll check back later and see if it's working

**Comment by shiftkey** [comment]
@ryangribble has Travis moved some cheese around?

```
E: Package 'dotnet-dev-1.0.1' has no installation candidate

The command "sudo apt-get install -qq dotnet-dev-1.0.1" failed and exited with 100 during .

Your build has been stopped.
```

**Comment by ryangribble** [comment]
Cool, found some guidance [here](https://github.com/travis-ci/travis-ci/issues/8793#issuecomment-346472509) that indicated the 1.0.1 sdk package isnt available in the package feed travis is now using.  Updated to 1.0.4 and all is well again :+1:

**Comment by ryangribble** [comment]
release_notes: Added `UpdatedAt` property to `Milestone` response class

**Pull request merged**
