### PR TITLE
Correcting return type in ObservableEventsClient

### PR DESCRIPTION
**Pull request by StanleyGoldman**
#1251 threw me for a loop for a bit.
It turns out this API deals in `IssueEvent` not `Activity`.

### CODE REVIEW

**Comment by StanleyGoldman** [comment]
Hmm, I might need some help understanding why the integration tests fail.
I supplied a username, organization, and token in `Octokit.Tests.Integration.Helper` and the rest seemed to work for me.

**Comment by shiftkey** [comment]
@StanleyGoldman these failures appear related to the unit tests - check the mocks locally as they may need to be updated.

Also, have you checked the [Slow Tests](https://github.com/octokit/octokit.net/blob/master/CONTRIBUTING.md#slow-tests) section in the CONTRIBUTING docs? That should help you setup your environment for testing.

**Comment by StanleyGoldman** [comment]
Hey @shiftkey I didn't see the Slow Tests documentation, I will definitely give it a try tonight.
It's just odd because I did what I feel was an equivalent locally, which passed during tests.
I'll let you know how it goes.

**Comment by StanleyGoldman** [comment]
@shiftkey Good to go.

**Comment by shiftkey** [comment]
@StanleyGoldman thanks!

**Pull request merged**
