### PR TITLE
React to change in the way the RepositoryTraffic API communicates time

### LINKED ISSUE #1558: Getting Exception thrown: 'System.FormatException' in mscorlib.dll when deserializing type RepositoryTrafficView
I am using the new API calls from Octokit .NET (3c818934 Release v0.24) , and I am getting a deserialization Exception:

System.FormatException occurred
  HResult=-2146233033
  Message=Input string was not in a correct format.
  Source=mscorlib
  StackTrace:
       at System.Number.StringToNumber(String str, NumberStyles options, NumberBuffer& number, NumberFormatInfo info, Boolean parseDecimal)
  InnerException: 

The method DeserializeObject fails at line 1401 of SimpleJson.cs:
return Convert.ChangeType(str, type, CultureInfo.InvariantCulture);

**str** contains: 
2017-02-08T00:00:00Z

**type** contains:
{Name = "Int64" FullName = "System.Int64"}

Values at line 165:

 return base.DeserializeObject(value, type);
**value**
{{"timestamp":"2017-02-08T00:00:00Z","count":2,"uniques":2}}

**type**
{Name = "RepositoryTrafficView" FullName = "Octokit.RepositoryTrafficView"}

It seems wrong to me that timestamp gets type of Int64.  I don't understand the code enought at this time to see what the problem is.

Thanks for your help.

### PR DESCRIPTION
**Pull request by mderriey**
Fixes #1558.
The API used to send times as number of seconds from Unix epoch time.
This has changed and is now ISO 8601.

### CODE REVIEW

**Comment by ryangribble** [comment]
Thanks @mderriey for the fix!

so it looks like appveyor builds are not playing nice.  and the travis linux builds are failing due to that same dotnetcore related issue that you fixed on the dotnetcore branch.  Did you want to cherry pick that travis fix into this branch so we can get master building?

I will try and figure out what the problem with AppVeyor is!

**Comment by mderriey** [comment]
Hey @ryangribble 

I cherry-picked the commit but this time even the Linux build failed :(. Could you please queue another one when you have the chance?

Cheers.

**Comment by ryangribble** [comment]
OK so the appveyor problem turned out to be account feed no longer being allowed for public projects.  We actually arent using this feed anyway but our appveyor.yml had the settings in it which I've now removed.
http://help.appveyor.com/discussions/problems/6024-build-stalled-prompting-for-nuget-permissions

**Comment by ryangribble** [comment]
Thanks for the fix @mderriey (and finally!  TravisCI and AppVeyor are passing again :) )

LGTM

**Comment by mderriey** [comment]
Cheers!

**Comment by ryangribble** [comment]
release_notes: Fix `RepositoryTrafficClient` to handle upstream change in timestamps from Unix epoch time to ISO8601

**Pull request merged**
