### PR TITLE
Release v0.27 - On a Roll

### PR DESCRIPTION
**Pull request by ryangribble**
Aiming to release this tomorrow

- [x] initial release notes
- [x] run `build FormatCode` to tidy up whitespace/formatting
- [x] ~~integration tests all pass~~ Except for some larger issues raised in #1686 
- [x] :thumbsup: from @shiftkey or @Haacked
- [ ] :thumbsup: from key contributors @mderriey @alfhenrik  @M-Zuber etc
- [ ] :shipit:

### CODE REVIEW

**Comment by shiftkey** [comment]
@ryangribble :thumbsup:

**Comment by mderriey** [comment]
@ryangribble That all looks good to me. Thanks again for that we'll polished release.

**Comment by Huhuhuhu12345** [comment]
Wow

**Comment by alfhenrik** [comment]
I'm not sure I should be counted as a *key contributor* any more...

**Pull request merged**
