### PR TITLE
Add missing `SecurityCritical` attribute

### LINKED ISSUE #1471: Mark RepositoryFormatException.GetObjectData with System.Security.SecurityCritical
I'm getting this exception when trying to run a program using Octokit in .NET Fiddle:

> [System.TypeLoadException: Inheritance security rules violated while overriding member: 'Octokit.RepositoryFormatException.GetObjectData(System.Runtime.Serialization.SerializationInfo, System.Runtime.Serialization.StreamingContext)'. Security accessibility of the overriding method must match the security accessibility of the method being overriden.]
  at Program.<GetIssues>d__5.MoveNext(): line 57

> [System.AggregateException: One or more errors occurred.]
  at Program.Main(String[] args): line 16

I think `RepositoryFormatException.GetObjectData` should be annotated with `System.Security.SecurityCritical`, [like its base version](http://referencesource.microsoft.com/#mscorlib/system/exception.cs,548).

I'll PR this if no one beats me to it :smile:

### PR DESCRIPTION
**Pull request by M-Zuber**
Fixes #1471

### CODE REVIEW

**Comment by khellang** [comment]
I approve of this :+1: Though there are other overrides of this as well; https://github.com/octokit/octokit.net/search?utf8=%E2%9C%93&q=GetObjectData

**Comment by M-Zuber** [comment]
👍 thanks for pointing that out, will get to them soon

**Comment by M-Zuber** [comment]
Done :)

**Comment by shiftkey** [comment]
@M-Zuber thanks!

**Pull request merged**
