### PR TITLE
Deliver the dotnetcore port and CAKE build framework changes

### PR DESCRIPTION
**Pull request by ryangribble**
I think the time has come to ship our `dotnetcore` port!

- [x] Updated to latest VS2017/msbuild tooling
- [x] AppVeyor and TravisCI builds are :gem:
- [x] SourceLink support came back into the picture 🎉 
- [x] CAKE build has all equivalent tasks that previous FAKE build had
- [x] Alpha release libraries were pushed to nuget (700+ downloads and no reported issues)
- [x] Update `dotnetcore` branch with latest `master`
- [x] Get #1579 and #1580 merged into master and then update `dotnetcore` again
- [x] Review any contributors guide/docs update required => #1600
- [x] :+1: from @shiftkey or @Haacked 

Unless anyone has any other items on the TODO list I think we can hit the button once those last couple of items are done!

/CC @shiftkey @Haacked @mderriey

### CODE REVIEW

**Comment by shiftkey** [comment]
Is there any particular feedback you need from me?

**Comment by ryangribble** [comment]
Nothing specific, unless you can spot anything I've missed!

**Comment by mderriey** [comment]
I'm confused. How can there still be conflicts when `master` was just merged into `dotnetcore`? Have I not done what I think I've done?

**Comment by ryangribble** [comment]
Could it be be because it squashed the PR instead of merge maybe?

**Comment by mderriey** [comment]
Right, that makes sense. I think it does. So this happens because we lost the merge commit from `master` to `dotnetcore`?

**Comment by ryangribble** [comment]
Ive pushed a merge commit and the conflicts aren't showing now.  It's interesting because locally the only 2 files on the merge were 2 csproj files, yet the github web interface was claiming conflicts in the linqpad files as well.  🤷‍♂️

**Comment by ryangribble** [comment]
FYI I've pushed a PR to do the mentioned doc updates (and as it turns out, a few more cleanup type tasks). 
 Once #1600 is merged into dotnetcore, we should be good to hit the button on this PR!

**Comment by ryangribble** [comment]
OK people, I'm going to do it... see you on the other side 😁 

LGTM

**Comment by M-Zuber** [comment]
]

**Pull request merged**
