### PR TITLE
Add a code formatting task to CAKE

### LINKED ISSUE #1547: [.NET Core] - Add CAKE code formatting task
As we shifted from FAKE to CAKE in #1503, we need to port the code formatting task used before a release to make sure the code style is consistent across the solution.

### PR DESCRIPTION
**Pull request by mderriey**
Closes #1547

### CODE REVIEW

**Comment by ryangribble** [comment]
@mderriey this is working nicely :+1:

One enhancement request I have is to add an info message to the log to state that it's generating a temporary csproj (so it's less confusing that the formatting tool then mentions csproj when we are a dotnetcore project)

```
========================================
FormatCode
========================================
Formatting code of Octokit
```
`  Generating temporary csproj file` <== add something like this
```
Octokit.csproj
        Syntax Pass
        Local Semantic Pass
        Global Semantic Pass
```

**Comment by mderriey** [comment]
@ryangribble 👍 to that.

**Comment by ryangribble** [comment]
Awesome :grinning:

If you can just merge/rebase on the target branch to pull in that travis fix, I can hit the button once the builds are 💚

**Comment by ryangribble** [comment]
LGTM

**Pull request merged**
