### PR TITLE
Remove `/en` slug in docs.github.com links (and stop VSCode from formatting on save)

### PR DESCRIPTION
**Pull request by SeanKilleen**
Supports #2474 

* Updates vs code settings file to stop format on save
* Removes `/en` from the existing docs.github.com links

### CODE REVIEW

**Comment by SeanKilleen** [comment]
@nickfloyd here's a smaller, targeted PR to start us off. Ready for review.

**Review by JonruAlveus — APPROVED** [review]
Looks great to me!

**Comment by nickfloyd** [comment]
release_notes: Removes `/en` slug in docs.github.com links (and stop VSCode from formatting on save)

**Comment by nickfloyd** [comment]
Thanks for taking this on and getting things started with docs here @SeanKilleen!  You're a 🦸!

**Pull request merged**
