### PR TITLE
v0.22 - Ridgy Didge

### PR DESCRIPTION
**Pull request by shiftkey**
Aiming to ship this **Wednesday 31 August** AEST. Running through the test suite today/tomorrow.

- [x] merge #1441
- [x] merge #1450 
- [x] merge #1452
- [x] rebase this branch
- [x] release notes (need to write up new obsoletions)
- [x] version bump
- [x] integration tests all pass
- [x] :thumbsup: from @Haacked or @ryangribble on release notes 
- [x] tag and publish to NuGet
- [x] :shipit:

### CODE REVIEW

**Comment by ryangribble** [comment]
Rather than only including the moving of methods to the branches API it would be good to get the top level branch protection stuff in this release.  It's ready to merge apart from :lipstick: #1407

**Comment by shiftkey** [comment]
@ryangribble so that's #1441 and #1443?

**Comment by ryangribble** [comment]
No, just #1441 .  That's enough to manage branch protections with the new API structure.  #1443 isnt ready yet, and is also just gravy (allows more granular editing of portions of branch protection, but they al lcan be set by the top level methods in #1441 anyway).

So yeah id like #1441 in this release if possible :)  Just addressing your comments now

**Comment by shiftkey** [comment]
@ryangribble :thumbsup:

**Comment by ryangribble** [comment]
Id also like to include #1450 in this release since its a trivial change but a much awaited feature

**Comment by shiftkey** [comment]
@ryangribble let me know if there's any other obsoletions I've missed here

**Comment by ryangribble** [comment]
I corrected one typo but I've realised I missed obsoleting some of the stuff on the observable interface... also now that the new branch protection methods are implemented we can actual direct users to the alternative/replacement methods rather than just saying those old ones "will cease to work".  Ill push a PR to fix up the wording etc now.

In terms of the branch protection stuff I dont know if its worth calling it out in the release notes somehow or not, but basically branch protection works fairly differently now (all due to the upstream changes made in github api).

Previously:
- `Branch` objects inclued a `Protection` field which contained all the branch protection settings, and you could enable/disable branch protection using the `client.Repository.EditBranch()` method (also now moved to `client.Repository.Branch.Edit()`).  

Now:
`Branch` objects have a `bool Protected` property, and an additional endpoint is required (`client.Repository.Branch.GetBranchProtection()` to get the actual protection settings (but it throws a 404 exception if protection is not actually enabled so you have to check that `Branch.Protected` flag first).  You edit protection settings using `client.Repository.Branch.UpdateBranchProtection()` and you disable protection using `client.Repository.Branch.DeleteBranchProtection()`

Im not sure how to summarize the nicely in the release notes though!

**Comment by shiftkey** [comment]
> Im not sure how to summarize the nicely in the release notes though!

I'll give it a shot - thanks for the initial start!

**Comment by shiftkey** [comment]
This is shipped:

 - https://www.nuget.org/packages/Octokit/0.22.0
 - https://www.nuget.org/packages/Octokit.Reactive/0.22.0

**Pull request merged**
