### PR TITLE
Added Environments API - GetAll list only feature

### PR DESCRIPTION
**Pull request by semyon-p**
Let's add Environment API support.
https://github.com/octokit/octokit.net/issues/2329

As a 1st step I've implemented GetAll methods for Environments.

### CODE REVIEW

**Comment by nickfloyd** [comment]
Hey @semyon-p Thank you so much for the contributions here.  If you get the chance, would you mind adding any test coverage that would be appropriate?  If needed, you can look at what others have done before you [here](https://github.com/octokit/octokit.net/tree/main/Octokit.Tests).

Thank you again for making things better! ❤️

**Review by nickfloyd — CHANGES_REQUESTED** [review]
Overall, things look good here.  Just a comment about the tests and also you'll need to add an interface to the Reactive Project - `Octokit.Reactive.IObservableRepositoryDeployEnvironmentsClient` we keep these in parity with the sync SDK APIs and interfaces.  Let me know if you need any help with any of this!  Thanks again for the contributions!

**Comment by semyon-p** [comment]
@nickfloyd hi!
I've added tests and IObservableRepositoryDeployEnvironmentsClient.
All tests are passed now. Please check.
I've made a small change in Octokit.Models.Request.ApiOptions class to become such kind of constructions work correctly:
            if (options != ApiOptions.None)
            {
               //do something
            }

**Comment by semyon-p** [comment]
@nickfloyd also I wanted to let you know, that I was trying to implement CreateEnvironment method but figured out, that API call described in the documentation does not work for me.
https://docs.github.com/en/rest/deployments/environments#create-or-update-an-environment
I've tried to test on a public personal repository.

DeleteEnvironment call works fine, by the way.
https://docs.github.com/en/rest/deployments/deployments#delete-a-deployment

Maybe I've done something wrong, but if you'll have some time please check it too. Maybe there is a bug in Github API itself.

**Review by nickfloyd — APPROVED** [review]

**Comment by mikebollandajw** [comment]
Value was either too large or too small for an Int32.    at System.Convert.ThrowInt32OverflowException()
         at System.Convert.ToInt32(Int64 value)
         at System.Convert.ChangeType(Object value, Type conversionType, IFormatProvider provider)
         at Octokit.PocoJsonSerializerStrategy.DeserializeObject(Object value, Type type) in /_/Octokit/SimpleJson.cs:line 1437
         at Octokit.PocoJsonSerializerStrategy.DeserializeObject(Object value, Type type) in /_/Octokit/SimpleJson.cs:line 1368
         at

**Pull request merged**
