### PR TITLE
Gist Comments API

### PR DESCRIPTION
**Pull request by khellang**
Here's an implementation of the gist comments API. The only thing missing should be some integration tests, I can add that later if you want :smile:

### CODE REVIEW

**Comment by Haacked** [comment]
@khellang Can you remind me why we needed the `BodyWrapper` class?

**Comment by khellang** [comment]
Uuuh. I don't really remember :confused: I think it might be because the API [expects an object and not just a string](https://developer.github.com/v3/gists/comments/#create-a-comment);

```json
{
  "body": "Just commenting for the sake of commenting"
}
```

**Comment by Haacked** [comment]
Ah, right. Maybe `BodyResponse` is a better name, but no need to change it for now.

**Comment by khellang** [comment]
If anything, it's a `BodyRequest` :wink: https://github.com/octokit/octokit.net/blob/1cea52eefa67d094e165b5f06a2d9dbad0330490/Octokit/Clients/GistCommentsClient.cs#L56

**Comment by Haacked** [comment]
Or `RequestBody`!

**Pull request merged**
