### PR TITLE
Fixes #1750, changing description of productInformation param for clarity

### LINKED ISSUE #1750: [Suggestion] GitHubClient.cs - clarify productInformation field in constructor
Hello,

Going through the [GitHubClient.cs file](https://github.com/octokit/octokit.net/blob/c9b2c1260bc87b7782d4fd9645d43a8885203923/Octokit/GitHubClient.cs) I noticed the constructor takes a `ProductHeaderValue` named `productInformation` with the XML documentation comments [(XMLDOC tags)](https://docs.microsoft.com/en-us/dotnet/csharp/programming-guide/xmldoc/xml-documentation-comments) for this parameter as follows:

`The name (and optionally version) of the product using this library. This is sent to the server as part of the user agent for analytics purposes.`

Doing a tad bit of digging in the [Connection.cs file](https://github.com/octokit/octokit.net/blob/c9b2c1260bc87b7782d4fd9645d43a8885203923/Octokit/Http/Connection.cs) I see this is used for the User-Agent header. However I feel the XMLDOC tags on GitHubClient.cs don't clearly reflect the [Developer Documentation](https://developer.github.com/v3/#user-agent-required) for this field, as it can be your app name, your organization's name, or your username. Additionally, the comment states it's for analytics purposes, however the documentation states `This allows us to contact you if there are problems.`

I suggest modifying the XMLDOC, and if you're okay with it I don't mind opening the PR after doing the edit myself.

I recently went through making my own GitHub client rather than using octokit (for personal project involving building it from scratch), and recognized the difference immediately to the point of digging around and finding out where this field is used (which ultimately is for the User-Agent portion of the header when formatting the JSON) to determine if it was the User-Agent portion I thought, or something else.

Feel free to @ me if you'd like me to go ahead and open a PR for this change in documentation.

### PR DESCRIPTION
**Pull request by WeiseCreations**
Fixes #1750

* This updates GitHubClient.cs, ProductHeaderValue.cs, Connection.cs, and EnterpriseProbe.cs to reflect proper XML Doc that links to the info on GitHub's Dev Doc on User-Agent required.
* Updates the description to reflect that docs state this is not just a product, but can be your organization name or username as well.
* I am submitting a bug to GitHub.com separately for a UI issue in comparing branches.
    * I initially used tabs instead of spaces on my first upload.
    * I then commited edits, removing all spaces by using Atom's Whitespace > Tabs to Spaces feature.
    * These commits also were mis-aligned on the UI.
    * I edited each file manually in the GitHub.com editor (within the browser).
    * These commits look fine when you inspect the file, but on compare are misaligned in some spots again by a space or two. This should look normal locally as I've recloned to a new directory and the files had no mis-alignment.

### CODE REVIEW

**Comment by WeiseCreations** [comment]
If someone wants to attempt to edit the files themselves to see about indentation, I'd be curious to know what you see on your end. For me, even using the GitHub.com editior and removing all whitespace, removing the CRLF (or LF) and then redoing the indentation still isn't fixing it, which is why I'm fairly certain it's just a UI bug on comparing branches for the pull request UI.

**Comment by ryangribble** [comment]
having a quick look it seems like you have tab characters there rather than spaces?

**Comment by WeiseCreations** [comment]
I know it appears that way but it's gotta be a bug. Even using the in browser editor they are spaces for me.

**Comment by WeiseCreations** [comment]
Thanks Ryan,

I'm at the airport about to hop on a flight or I'd do it, haha. For me, all local files had spaces and on my fork they were spaces in browser. I committed multiple times deleting the line(s) and retyping with spaces.

It may be a cache issue, but I went ahead and submitted a bug report to GitHub with steps I took just in case.

**Comment by ryangribble** [comment]
Yeah that worked ok for me.  Must be something strange happening on your browser

What does my commit https://github.com/octokit/octokit.net/pull/1751/commits/a1d582ef32ed30a5a22034b24db03c09ecb92d73 look like to you?

**Comment by WeiseCreations** [comment]
From my phone, looks like the remarks are lined up and now the params are off (or are still off, can't recall if last night they too were misaligned).

I apologize for you having to go to try to fix something as simple as tabs versus spaces, heh.

**Comment by ryangribble** [comment]
> From my phone, looks like the remarks are lined up and now the params are off (or are still off, can't recall if last night they too were misaligned).

Oops i think I just missed that line 25 one.  

Anyway I think all files are fixed now, things look OK from this end at least!

**Comment by ryangribble** [comment]
release_notes: Clarified `ProductHeaderValue` usage to align with GitHub API Docs

**Comment by ryangribble** [comment]
Thanks @WeiseCreations for the contribution!

LGTM

😁 😁 😁

**Comment by WeiseCreations** [comment]
Thanks @ryangribble for the fix and merge. #teamwork #tabsarebetter #savethekeystrokes

Wish editors would resolve tab/space things on their own, heh. I swear all my local copies showed spaces only using Atom, VS, even notepad++ haha.

**Comment by ryangribble** [comment]
FYI @IAmHughes some of the commits on this PR are from an unknown (to GitHub) email address, and won't count in your contributions graph.  You can [add it as a secondary email address](https://github.com/settings/emails) to your profile so that they are included in your account/contributions :+1:

image

**Comment by IAmHughes** [comment]
@ryangribble I don't see the ? icon that should tell me which email is under the commit. Any help?

I've been changing some things (such as my profile name) on my account, that may be the issue.

**Comment by ryangribble** [comment]
True, it doesn't have the question mark... But I'm pretty sure everything is tracked by the email address of ultimately

**Comment by IAmHughes** [comment]
ah well. i dont mind :P

**Comment by ryangribble** [comment]
My only issue is it looks odd in the auto generated release notes :😁

Some info here https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/

**Comment by IAmHughes** [comment]
Unfortunately I believe its due to the anonymous email I use as part of GitHub's privacy on profiles (options 2/3 of the diagnoses). Both fixes listed actually say that there's not a way to fix old commits.

**Comment by ryangribble** [comment]
Anonymous email as in it's from a domain github won't recognise?

**Comment by IAmHughes** [comment]
Non anonymous as in on your profile at GitHub, there's a privacy setting to hide your email. https://help.github.com/articles/about-commit-email-addresses/, see bold "Keep your email address private"

**Pull request merged**
