### PR TITLE
 [WIP] Implement Repository Hooks & Repository Forks

### PR DESCRIPTION
**Pull request by johnduhart**
This replaces #313. I've rebased it with master, and cleaned up a few things that were missing on the original PR. This is what's left

- [ ] Write integration tests
 - [ ] For Hooks API
 - [ ] For Forks API

Anything else?

### CODE REVIEW

**Comment by gitspirit** [comment]
Any plans to merge it into master?

**Comment by kristianhald** [comment]
Three questions.
1) Is this pull request dead or is it still expected to be merged?
2) Is it only waiting for integration tests that are missing before it can be merged?
3) Where is the code located, so that the tests can be added, if they are only the missing prerequisites?

**Comment by shiftkey** [comment]
Three questions.
1) Is this pull request dead or is it still expected to be merged?
2) Is it only waiting for integration tests that are missing before it can be merged?
3) Where is the code located, so that the tests can be added, if they are only the missing prerequisites?

**Comment by kristianhald** [comment]
Working on this, but is slow going, as I can not execute the tests with my Resharper. I can see that the update to the XUnit tests has been merged into master and I have tried running the tests on master and it works very well on my computer.

What is the prefered way of getting master into my feature branch. Can I just do a merge from master to my branch or do I need to rebase it (As the original pr is old there is alot of manually handling the rebase).

**Comment by Haacked** [comment]
Either is fine: merge or Rebase. Whatever is easier.

**Pull request closed without merging**
