### PR TITLE
Handle event ids greater than int32.maxvalue

### PR DESCRIPTION
**Pull request by matt-richardson**
Fixes https://github.com/octokit/octokit.net/issues/1939

### CODE REVIEW

**Comment by ryangribble** [comment]
Thanks @matt-richardson 

LGTM

**Comment by matt-richardson** [comment]
Thanks for the quick response. Whats your thoughts around when this could make it into a release?

**Comment by ryangribble** [comment]
I've been meaning to push a release already however there wasn't anything that was urgent/pressing. This PR changes that though so I'll try to do it in the next few days. 

In the meantime you can pull the package built from merging this PR from our appveyor nuget feed if you need to get back up and running 👍

**Comment by ryangribble** [comment]
release_notes: Update `EventInfo.Id` field from `int` to `long` to prevent overflow exceptions

**Comment by adamralph** [comment]
Any update on getting this released? We're currently blocked on this over at https://github.com/Particular

**Comment by hnrkndrssn** [comment]
@adamralph you could use the beta package https://github.com/octokit/octokit.net/blob/master/README.md#beta-packages

That's how we unblocked ourselves while waiting for the next release.

**Comment by adamralph** [comment]
@hnrkndrssn in our case, we're using LINQPad scripts, and unfortunately we can't bake a package source into the script definitions.

**Comment by Eilon** [comment]
I just hit this as well with some events with IDs greater than int.MaxValue. Would love to see a public release that has this fix!

**Comment by Thraka** [comment]
I just ran into this issue too.

```csharp
var results = await client.Issue.Events.GetAllForRepository("dotnet", "docs");
```

Using octokit 0.36.0

**Comment by shiftkey** [comment]
@Thraka please open a new issue as I suspect that requires a different fix to what was addressed in this PR.

**Pull request merged**
