### PR TITLE
IRepositoriesClient.Commits -> IRepositoriesClient.Commit

### LINKED ISSUE #1035: IRepositoriesClient.Commits -> IRepositoriesClient.Commit
This is a pluralized interface that we shouldn't really have:

https://developer.github.com/v3/repos/commits/

```csharp
var commit = await github.Repository.Commits.Get("octokit", "octokit.net", "master");
```

We should mark this property as obsolete and introduce a new property which is singular:

```csharp
var commit = await github.Repository.Commit.Get("octokit", "octokit.net", "master");
```

### PR DESCRIPTION
**Pull request by M-Zuber**
Fixes #1035

[Review on Reviewable](https://reviewable.io/reviews/octokit/octokit.net/1042)

### CODE REVIEW

**Comment by shiftkey** [comment]
Merge conflicts :cry:

**Comment by M-Zuber** [comment]
Do you need that empty commit rebased out?

**Comment by Haacked** [comment]
> Do you need that empty commit rebased out?

Yes please. :smile:

**Comment by M-Zuber** [comment]
git history was messed up real bad.
Opening a new PR @ #1057

**Pull request closed without merging**
