### PR TITLE
Remove obsoleted repository update constructor of RepositoryUpdate

### PR DESCRIPTION
**Pull request by eriawan**
This is a PR to remove obsoleted paramless constructor of RepositoryUpdate, it is related to issue #1568

### CODE REVIEW

**Comment by eriawan** [comment]
@shiftkey @ryangribble please review.

**Comment by eriawan** [comment]
@ryangribble any updates on this? Do you want me to wait for other work in progress to be completed before approving and merging my PR?

cc @shiftkey

**Comment by shiftkey** [comment]
@eriawan I don't think so. Thanks for the contribution!

**Comment by eriawan** [comment]
You're welcome, @shiftkey 👍

**Comment by ryangribble** [comment]
Sorry for the delay on this one @eriawan I was planning on just running the integration tests but hadnt had time.  Can pick it up on the next release anyway.

We actually need to remove all the obsolete items from -2 releases ago

**Comment by eriawan** [comment]
@ryangribble no problem! 🙂 

I'll try to fix the remaining obsoleted items in a separate PR. Or do you want me to wait until you finish your integration test?

thanks for the reply 👍

**Comment by ryangribble** [comment]
No need to wait! That would be great thanks 😀

**Comment by ryangribble** [comment]
release_notes: Remove obsolete constructor of `RepositoryUpdate` request class

**Pull request merged**
