### PR TITLE
Clarifies usage of reference in IReferencesClient methods

### PR DESCRIPTION
**Pull request by Cyberboss**
Details the format of the reference parameter

### CODE REVIEW

**Comment by ryangribble** [comment]
Should this clarification also be made to the other methods in this client?

**Comment by ryangribble** [comment]
Hey @Cyberboss, can you tick the "Allow edits from maintainers" option on this PR, as I have made this doc update for the other places `reference` parameter is used (also updated the implementation class, and the `IObservableReferencesClient` interface and implementation as well) but am unable to push the changes

**Comment by Cyberboss** [comment]
Hmm, that's odd, it's checked on my end.

**Comment by ryangribble** [comment]
release_notes: Clarify the usage of `reference` parameter in `IReferencesClient` methods

**Pull request merged**
