### PR TITLE
Remove other obsoleted methods except Branch protection related methods (part 1)

### PR DESCRIPTION
**Pull request by eriawan**
This is the next removal of obsoleted methods, while waiting for Branch protection API review. Therefore removal of obsoleted methods will not touch Branch protection API (obsoleted) methods.
I deliberately submit this PR first to notify that this is part 1 of the obsoleted method removal to ease PR review.

cc @ryangribble @shiftkey

### CODE REVIEW

**Comment by eriawan** [comment]
Aha, the check comes. I'm fixing it now.

**Comment by eriawan** [comment]
@ryangribble and @shiftkey 

I have done removals of some obsoleted methods, and also checked the unit tests. Please review 🙂

**Comment by ryangribble** [comment]
Thanks @eriawan I will have a review this long weekend but just a note on those last couple of commits.  I think those tests can be completely removed as there should already be tests for the `Repository.Branch.Get/GetAll` methods in the appropriate file.  Let me know if I'm not making sense, I'm on my phone 😛

**Comment by eriawan** [comment]
Thanks @ryangribble ! 🙂 

Yes, I agree about the tests removed. I think I can remove those tests on a separate PR.
I'll move on to next PR to remove those test after you finish reviewing this PR. Have a good weekend! 👍

**Comment by ryangribble** [comment]
It looking pretty good, but the obsolete RepositoryContentsClientTests tests should be removed on this PR too, not much point in doing 2 PR's for the one change

**Comment by eriawan** [comment]
Thanks for your reply, @ryangribble 
OK, in this PR I will add more commits that remove the obsolete RepositoryContentsClientTests unit tests.

**Comment by ryangribble** [comment]
Superceded by #1622

**Comment by eriawan** [comment]
@ryangribble already done? 
apologize for the long delay. thanks for the update!

**Pull request closed without merging**
