### PR TITLE
Add ApiOptions overloads to methods on I(Observable)NotificationsClient

### LINKED ISSUE #1163: Add ApiOption overloads to methods on INotificationsClient
As part of completing #760 a number of overloads need to be added to the client interfaces.

As an example, this has been added to [`IReleasesClient`](https://github.com/octokit/octokit.net/commit/03ea83148995711fc47148489e2123e65f33bd82)and [`IObservableReleasesClient`](https://github.com/octokit/octokit.net/commit/aa3ce0db9210b778414e290af7f17c4a646bdeec).

The checklist for porting each method is:

- Add an overload for this method on `INotificationsClient` with a new parameter `ApiOptions`
- Implement the new method on the class which implements `INotificationsClient`
- Add an overload for this method on `IObservableNotificationsClient` with a new parameter `ApiOptions`
- Implement the new method on the class which implements `IObservableNotificationsClient`

This needs to be done for each of these methods:

- [ ] `Task<IReadOnlyList<Notification>> GetAllForCurrent()`
- [ ] `Task<IReadOnlyList<Notification>> GetAllForCurrent(NotificationsRequest request)`
- [ ] `Task<IReadOnlyList<Notification>> GetAllForRepository(String owner, String name)`
- [ ] `Task<IReadOnlyList<Notification>> GetAllForRepository(String owner, String name, NotificationsRequest request)`

### PR DESCRIPTION
**Pull request by dampir**
Fixes #1163 

To-do:

- [x]  Add overloads on INotificationsClient
- [x]  Add overloads on IObservableNotificationsClient
- [x]  Add unit tests for these new methods
- [x]  ~~Add integration tests for these new methods~~
        
     It's seems like now we do not have ability to create integration tests for I(Observable)NotificationsClient. I've opened issue #1333 to discuss it in details.

     

/cc @shiftkey, @ryangribble

### CODE REVIEW

**Comment by shiftkey** [comment]
> So what we are going to do here?

For the sake of simplicity, let's open a separate issue to talk about the integration tests and what we should do there (your notes seem accurate) and focus on the API changes for now.

**Comment by shiftkey** [comment]
This looks good, just that merge conflict to sort out...

**Comment by dampir** [comment]
@shiftkey I going to handle this merge conflict tomorrow, not have access to PC at this moment (I had a 2 day trip to Moscow in US embassy to get visa, so tomorrow I'm going to be home and I will fix that 👍 )

**Comment by dampir** [comment]
@shiftkey I've rebased this one, just plesky travis failed again. Please merge it whenever possible :+1:

**Pull request merged**
