### PR TITLE
Expose affiliation parameter when listing collaborators

### LINKED ISSUE #2036: List collaborators does not expose the affiliation parameter (or preview API)
https://developer.github.com/v3/repos/collaborators/#list-collaborators

https://github.com/octokit/octokit.net/blob/8b263cdc0f80102d358bd78dcb58151537e7e847/Octokit/Clients/RepoCollaboratorsClient.cs#L23-L86

Two things need to be added here:

 - support for `affiliation` - this should be a new enum and not our current [`RepositoryAffiliation`](https://github.com/octokit/octokit.net/blob/74dc51a6f567395d0c46d97f7270f959d671573e/Octokit/Models/Request/RepositoryRequest.cs#L170).

 - support for the nested teams preview API,  which has been available for a while

Screen Shot 2019-10-24 at 9 18 45 AM

cc @terrajobst as you were interested in this

### PR DESCRIPTION
**Pull request by hnrkndrssn**
Also adds support for the `Nested Teams` preview API

Fixes #2036

### CODE REVIEW

**Comment by shiftkey** [comment]
@hnrkndrssn I'm feeling pretty good with how this looks. Anything you're waiting on?

**Comment by hnrkndrssn** [comment]
> Anything you're waiting on?

I was going to write some tests for it, just got side tracked with life-stuff :) I'll try to get those last little things in tonight and mark the PR ready for review once done 👍

**Comment by shiftkey** [comment]
release_notes: add support for filtering repository collaborators by their affiliation

**Comment by Jacobtarango21** [comment]
image

**Pull request merged**
