### PR TITLE
Add support for StatusEventPayload

### PR DESCRIPTION
**Pull request by itaibh**
Added payload definition for the Status Event message.

  - [x] Write basic code.
  - [x] Make sure the code design fits the rest of the library.
  - [x] Write tests.

### CODE REVIEW

**Comment by ryangribble** [comment]
Hi @itaibh 

Thanks for the PR... in order to better understand your intentions could you please provide a brief description?   also to understand whether you think you are "done" or not, would could you please mark [WIP] in the title if you aren't done yet, and also provide a task list that are checked/unchecked, so we know what you still aim to do? 

Eg in this case a new payload class needs to be added to the special switch statement in the deserializer code and of course we need tests to prove it actually works 😁

**Comment by ryangribble** [comment]
Looks good @itaibh , if you have finished working on it, can you remove `[WIP]` (work in progress) from the PR title so we know it's ready ffrom your perspective?

**Comment by itaibh** [comment]
Hi @ryangribble!
Thank you. I consider it ready, and have removed the [WIP] tag.

**Comment by ryangribble** [comment]
release_notes: Support `StatusEvent` payloads, using new response model `StatusEventPayload`

**Comment by ryangribble** [comment]
Thanks @itaibh and congratulations on your first octokit contribution!

LGTM

**Pull request merged**
