### PR TITLE
Dev container rework to support OmniSharp changes

### PR DESCRIPTION
**Pull request by nickfloyd**
These changes are needed so that when working on code spaces and on OmniSharp server will properly start - https://github.com/OmniSharp/omnisharp-vscode#requirements

### CODE REVIEW

**Comment by nickfloyd** [comment]
> Does Omnisharp start for you with these changes? It doesn't for me. If I try to run the 'Restart OmniSharp' command for the command palette, I also get an error like this.

Odd I've never seen that error.  I am assuming steps to repro are:
1. Spin up a code space using this branch
2. Restart OmniSharp.

Quick question, we're you prompted to restart OmniSharp or did you just run the command out of habit?

Validate my assumed steps to repo - perhaps we can pair on it as well some time.

**Comment by timrogers** [comment]
> > Does Omnisharp start for you with these changes? It doesn't for me. If I try to run the 'Restart OmniSharp' command for the command palette, I also get an error like this.
> 
> Yes it starts right away. Odd I've never seen that error. I am assuming steps to repro are:
> 
> 1. Spin up a code space using this branch
> 2. Restart OmniSharp.
> 
> Validate my assumed steps to repo - perhaps we can pair on it as well some time.

Exactly. I did that, and that's what I'm seeing. Also worth noting that IntelliSense etc. doesn't work for me.

**Comment by timrogers** [comment]
I just ran the command because I saw IntelliSense wasn't working and I thought it might help. It seems that all the OmniSharp related commands generated similar errors.

**Comment by nickfloyd** [comment]
> I just ran the command because I saw IntelliSense wasn't working and I thought it might help. It seems that all the OmniSharp related commands generated similar errors.

Interesting... Would you mind sharing what you are seeing in the VS Code "Output" window after the code space is generated?

Generally you'll see something like:
Screen Shot 2022-06-10 at 9 17 29 AM

**Review by timrogers — APPROVED** [review]
I restarted my container and it worked 🤔  What do you think of merging this, and coming back later if we or others run into issues?

**Comment by nickfloyd** [comment]
release_notes: Adds support to the dev container for OmniSharp

**Pull request merged**
