### PR TITLE
Release of v0.16 - ironic ties

### PR DESCRIPTION
**Pull request by Haacked**
- [x] Release notes and
- [x] bumped version
- [x] integration tests passed

### CODE REVIEW

**Comment by forki** [comment]
:heart:

**Comment by Haacked** [comment]
@forki could you do me a favor? Pull down this branch and run `.\build.cmd CreatePackages`

It's failing for me. :frowning:

**Comment by forki** [comment]
Would love to,  but I just started my vacation. I'm off sailing for one week. Sorry

**Comment by Haacked** [comment]
@forki have a great trip! Who will fix the F# ecosystem in your place once we get these packages published?

**Comment by forki** [comment]
That's easy. People will just do "paket update nuget Octokit" and
everything will work again. ;-)

See you in a week

**Comment by niik** [comment]
These notes looks good to me :+1:

**Pull request merged**
