### PR TITLE
add NET Core

### PR DESCRIPTION
**Pull request by ShalokShalom**

### CODE REVIEW

**Comment by ryangribble** [comment]
Fyi we actually support net core 1.0 onwards...

Though I think it would be better to state netstandard 1.1 rather than a net core version, and possibly hyperlink it to Microsoft page showing the netstandard versions and what each one aligns with

**Comment by ShalokShalom** [comment]
Yep

**Comment by ryangribble** [comment]
I've updated the PR to show what I mean... do you think this is sufficient?

**Comment by ryangribble** [comment]
Yes, .NET Standard versions are cumulative, so by supporting .NET Standard 1.1 any framework that implements 1.1 or later, will be able to consume Octokit

**Comment by ryangribble** [comment]
Update supported platforms in README.md to include `.NET Standard 1.1`

**Comment by ShalokShalom** [comment]
So mean that higher versions are also supported? Might be confusing otherwise.

**Pull request merged**
