### PR TITLE
Add repositoryId overloads to methods on I(Observable)MergingClient

### PR DESCRIPTION
**Pull request by dampir**
As part of my work on #1120 I've added new overloads on I(Observable)MergingClient to get access by repository id.

- [x] **Update XML documentation of interface methods of clients (also synchronize XML docs of IMergingClient and IObservableMergingClient).**

	  There is some divergence between XML documentation of methods in IMergingClient and IObservableMergingClient. So I've decided 
	  to sync XML documentation of these classes during my work on #1120.
- [x] **Add overloads to IMergingClient.**

	  Just add overloads of existing methods that use repositoryId to work with repo.
- [x] **Add overloads to IObservableMergingClient.**

	  Just add overloads of existing methods that use repositoryId to work with repo.
- [x] **Add unit tests.**

	  I've added new unit tests that use repositoryId to work with repo that is just a full copy of existing tests that use (owner, name) key.
	  Also I've found out that not all methods are covered by tests and added them for new and for old methods.
- [x] **Add integration tests.**

	  I've added new integration tests that use repositoryId to work with repo that is just a full copy of existing tests that use (owner, name) key.
	  Also I've found out that not all methods are covered by tests and added them for new and for old methods.

/cc @shiftkey, @ryangribble

### CODE REVIEW

**Comment by dampir** [comment]
no need to update <returns>, they are empty.

**Comment by shiftkey** [comment]
@dampir are you able to rebase this branch? There's a lot of changes in here which seem unrelated to the initial PR, and make reviewing much more tedious...

**Comment by dampir** [comment]
@shiftkey done :+1:

**Comment by ryangribble** [comment]
This one is good to merge, once the empty `<returns></returns>` tags are removed :+1:

**Comment by ryangribble** [comment]
Actually, since the methods in this client already had empty `<returns></returns>` tags, I don't think this  needs to be addressed in this PR since you didn't clear the tags.  Another PR can clean this up

**Pull request merged**
