### PR TITLE
Docs: search users

### PR DESCRIPTION
**Pull request by hahmed**
Search dem users documentation.

Edit: something gone wrong with the commit history, sorry!

### CODE REVIEW

**Comment by shiftkey** [comment]
If you want to get rid of those changes:

> git reset octokit/documentation --hard
> git cherry-pick d80b8a31

and then force push it away...

**Comment by hahmed** [comment]
@shiftkey force push it away? Sorry, I do not have a clue what that means.

git push origin docs-search-users --force ?

**Comment by shiftkey** [comment]
@hahmed that's the one!

**Comment by Haacked** [comment]
Be careful with `--force`. It rewrites history on the server. It's probably fine in this case, but if you ever do it to `master` on a shared project, you'll be making a lot of people unhappy. :smile:

**Comment by hahmed** [comment]
I just get an everything is up to date. Nothing has changed in this PR. Looks like I am doing something wrong. @Haacked thanks for the heads up, I will keep that in mind.

**Pull request closed without merging**
