### PR TITLE
Fixed Add Author To Release Response

### LINKED ISSUE #1008: Add Author To Release Response
Author is data returned from the `releases` endpoint, which is not accessible from OctoKit.Net.

```
  {
    "url": "https://api.github.com/repos/aspnet/Razor/releases/2127185",
    "assets_url": "https://api.github.com/repos/aspnet/Razor/releases/2127185/assets",
    "upload_url": "https://uploads.github.com/repos/aspnet/Razor/releases/2127185/assets{?name,label}",
    "html_url": "https://github.com/aspnet/Razor/releases/tag/4.0.0-rc1",
    "id": 2127185,
    "tag_name": "4.0.0-rc1",
    "target_commitish": "release",
    "name": "4.0.0-rc1",
    "draft": false,
    "author": {
      "login": "danroth27",
      "id": 1874516,
      "avatar_url": "https://avatars.githubusercontent.com/u/1874516?v=3",
      "gravatar_id": "",
      "url": "https://api.github.com/users/danroth27",
      "html_url": "https://github.com/danroth27",
      "followers_url": "https://api.github.com/users/danroth27/followers",
      "following_url": "https://api.github.com/users/danroth27/following{/other_user}",
      "gists_url": "https://api.github.com/users/danroth27/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/danroth27/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/danroth27/subscriptions",
      "organizations_url": "https://api.github.com/users/danroth27/orgs",
      "repos_url": "https://api.github.com/users/danroth27/repos",
      "events_url": "https://api.github.com/users/danroth27/events{/privacy}",
      "received_events_url": "https://api.github.com/users/danroth27/received_events",
      "type": "User",
      "site_admin": false
    },
    "prerelease": true,
    "created_at": "2015-11-18T20:03:10Z",
    "published_at": "2015-11-18T15:28:35Z",
    "assets": [

    ],
    "tarball_url": "https://api.github.com/repos/aspnet/Razor/tarball/4.0.0-rc1",
    "zipball_url": "https://api.github.com/repos/aspnet/Razor/zipball/4.0.0-rc1",
    "body": "### Features\r\n\r\n* API namespace cleanup for tag helpers ([#578](https://github.com/aspnet/Razor/issues/578))\r\n* Refactor WriteAttribute API surface. ([#177](https://github.com/aspnet/Razor/issues/177))\r\n\r\n### Bugs Fixed\r\n\r\n* Multiple TagHelpers targeting same element cannot effectively communicate to children. ([#571](https://github.com/aspnet/Razor/issues/571))\r\n* Compilation error within tag attribute shows generated code instead of markup ([#569](https://github.com/aspnet/Razor/issues/569))\r\n* Specifying `RestrictChildren` and empty `HtmlTargetElement` results in an error ([#562](https://github.com/aspnet/Razor/issues/562))\r\n* `TreeStructureChanged` marked as `true` when whitespace is added to a page with `TagHelper`s ([#553](https://github.com/aspnet/Razor/issues/553))\r\n* Expose `FilePath` on `MappingLocation` to let Razor editor know mapping origination. ([#552](https://github.com/aspnet/Razor/issues/552))\r\n\r\n"
}
```

### PR DESCRIPTION
**Pull request by gabrielweyer**
Fixes #1008 

Added `Author` to `Release` response. Added integration test ensuring login is set on `Author` property.

I noticed that some other properties are missing too:
 - `assets` (this is an object)
 - `tarball_url`
 - `zipball_url`

Do we want to add those too?

Sample response:

```json
{
	"url": "https://api.github.com/repos/git-tfs/git-tfs/releases/2276624",
	"assets_url": "https://api.github.com/repos/git-tfs/git-tfs/releases/2276624/assets",
	"upload_url": "https://uploads.github.com/repos/git-tfs/git-tfs/releases/2276624/assets{?name,label}",
	"html_url": "https://github.com/git-tfs/git-tfs/releases/tag/v0.24.1",
	"id": 2276624,
	"tag_name": "v0.24.1",
	"target_commitish": "master",
	"name": "",
	"draft": false,
	"author": {
		"login": "spraints",
		"id": 20158,
		"avatar_url": "https://avatars.githubusercontent.com/u/20158?v=3",
		"gravatar_id": "",
		"url": "https://api.github.com/users/spraints",
		"html_url": "https://github.com/spraints",
		"followers_url": "https://api.github.com/users/spraints/followers",
		"following_url": "https://api.github.com/users/spraints/following{/other_user}",
		"gists_url": "https://api.github.com/users/spraints/gists{/gist_id}",
		"starred_url": "https://api.github.com/users/spraints/starred{/owner}{/repo}",
		"subscriptions_url": "https://api.github.com/users/spraints/subscriptions",
		"organizations_url": "https://api.github.com/users/spraints/orgs",
		"repos_url": "https://api.github.com/users/spraints/repos",
		"events_url": "https://api.github.com/users/spraints/events{/privacy}",
		"received_events_url": "https://api.github.com/users/spraints/received_events",
		"type": "User",
		"site_admin": true
	},
	"prerelease": false,
	"created_at": "2015-12-12T03:10:45Z",
	"published_at": "2015-12-12T03:12:47Z",
	"assets": [
		{
			"url": "https://api.github.com/repos/git-tfs/git-tfs/releases/assets/1121275",
			"id": 1121275,
			"name": "GitTfs-0.24.1.zip",
			"label": null,
			"uploader": {
				"login": "spraints",
				"id": 20158,
				"avatar_url": "https://avatars.githubusercontent.com/u/20158?v=3",
				"gravatar_id": "",
				"url": "https://api.github.com/users/spraints",
				"html_url": "https://github.com/spraints",
				"followers_url": "https://api.github.com/users/spraints/followers",
				"following_url": "https://api.github.com/users/spraints/following{/other_user}",
				"gists_url": "https://api.github.com/users/spraints/gists{/gist_id}",
				"starred_url": "https://api.github.com/users/spraints/starred{/owner}{/repo}",
				"subscriptions_url": "https://api.github.com/users/spraints/subscriptions",
				"organizations_url": "https://api.github.com/users/spraints/orgs",
				"repos_url": "https://api.github.com/users/spraints/repos",
				"events_url": "https://api.github.com/users/spraints/events{/privacy}",
				"received_events_url": "https://api.github.com/users/spraints/received_events",
				"type": "User",
				"site_admin": true
			},
			"content_type": "application/zip",
			"state": "uploaded",
			"size": 8703010,
			"download_count": 148,
			"created_at": "2015-12-12T03:15:42Z",
			"updated_at": "2015-12-12T03:15:57Z",
			"browser_download_url": "https://github.com/git-tfs/git-tfs/releases/download/v0.24.1/GitTfs-0.24.1.zip"
		}
	],
	"tarball_url": "https://api.github.com/repos/git-tfs/git-tfs/tarball/v0.24.1",
	"zipball_url": "https://api.github.com/repos/git-tfs/git-tfs/zipball/v0.24.1",
	"body": "* Fix problems with 0.24.0 (#886, #887)\r\n"
}
```

### CODE REVIEW

**Comment by shiftkey** [comment]
> Do we want to add those too?

Sure!

**Comment by gabrielweyer** [comment]
Added everything that was missing. Left out `gravatar_id` from the user payload as it has been [deprecated](https://developer.github.com/changes/2014-09-05-removing-gravatar-id/).

**Comment by gabrielweyer** [comment]
I didn't run the build script locally, I'm a bad man :cold_sweat:

**Comment by shiftkey** [comment]
> I didn't run the build script locally, I'm a bad man :cold_sweat:

**Comment by Haacked** [comment]
Looks good to me!


selfie-1

**Pull request merged**
