### PR TITLE
[feat]: Add RenameBranch method to RepositoryBranchesClient

### PR DESCRIPTION
**Pull request by dirtygooback**
Resolves #ISSUE_NUMBER

----

### Before the change?

* The RenameBranch method was not available on the RepositoryBranchClient object

### After the change?

* The Rename Branch method has been added to the RepositoryBranchClient object

### Pull request checklist
- [x] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been reviewed and added / updated if needed (for bug fixes / features)

### Does this introduce a breaking change?

Please see our docs on [breaking changes](https://github.com/octokit/.github/blob/master/community/breaking_changes.md) to help!

- [ ] Yes
- [x] No

----

### CODE REVIEW

**Review by nickfloyd — CHANGES_REQUESTED** [review]
Hey @dirtygooback Thanks for the adds here! ❤️ 

Would you mind converting your tabs to spaces? Optionally you can set you fork to maintainer writes and I can get it knocked out!

Thanks again!

**Comment by nickfloyd** [comment]
> if you like spaces over tabs that's on you :) The fork should already allow edits by maintainer

Heh, it's not that I prefer them one way or the others, it's that the entire project favors spaces. We should really have a linter that checks for this and warns.

As far as [allowing edits by maintainers](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/working-with-forks/allowing-changes-to-a-pull-request-branch-created-from-a-fork) - I am getting the following which typically means that a user-owned fork does not allow edits from maintainers.  I'll try making the changes outside of a code space to see if that's the issue.
 
Screenshot 2023-10-11 at 1 39 59 PM

**Comment by ddaniels-andmore** [comment]
Let me know if I need to do anything to the repo. Happy to help

**Comment by nickfloyd** [comment]
I did not.  It seems for whatever reason I cannot push commits to your fork. Assuming your settings on the fork align with what's detailed [here](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/working-with-forks/allowing-changes-to-a-pull-request-branch-created-from-a-fork), I have no idea what's going on.

The options are:
1. I let this in and then do a quick follow up with the fixes to make sure the repo remains standardized and add a linter to prevent this in the future.
2. You make the changes in your fork and I merge it in and put an item in the backlog for a linter to enforce this.

At this point, I could go either way.  The functionality here is good and would provide value, which I am more interested in getting value to the community over trying to stick with a standard, but I am blocked today with our other duties and won't be able to get to the changes needed until tomorrow.  Sorry for the trouble - if you feel compelled to make the spacing changes that would be awesome, but I understand our lack of enforced protocol is making this a bit more inconvenant .  

Let me know what you'd be up for, I am good either way and really just want the value shipped.

**Comment by dirtygooback** [comment]
@nickfloyd - It's not my repo so I changed the tabs to spaces. Hope I got them all. I do agree that if this is something that needs to be enforced, a linter will go a long way. I'm a TABs guy :) :)

**Comment by dirtygooback** [comment]
@nickfloyd - is there anything more that needs to be done to this PR before it gets merged?

**Review by kfcampbell — APPROVED** [review]

**Pull request merged**
