### PR TITLE
Adding RemovedFromProject and other missing EventInfoState types.

### PR DESCRIPTION
**Pull request by lynnfaraday**
The problem described in PR #1536 / Issue #1502 cropped up again.  Apparently GitHub has added more event types.  

This change incorporates all of the states in the [GitHub API](https://developer.github.com/v3/issues/events/) plus some undocumented ones we encountered during prior testing.  

I put them in the order that they're listed in the GitHub API so you can easily skim the list and compare.

### CODE REVIEW

**Comment by shiftkey** [comment]
@lynnfaraday :thumbsup: all seems reasonable. I'll let @ryangribble or someone else have a look before I merge it.

**Comment by M-Zuber** [comment]
👌

**Comment by ryangribble** [comment]
LGTM

**Comment by karelz** [comment]
FYI: I have validated the changes on all dotnet/Roslyn repo. All 3 cases I hit there (https://github.com/octokit/octokit.net/issues/1594#issuecomment-297652513) were addressed by this list.

**Comment by ryangribble** [comment]
release_notes: Fix even more `IssueTimelineClient` deserialization exceptions by adding even more new `EventInfoState` values (this is getting old!)

**Pull request merged**
