### PR TITLE
Response caching

### LINKED ISSUE #2649: [FEAT]: add caching funtionality for GET responses
### Describe the need

Github has a default 5000 API req/hour limit, see https://docs.github.com/en/developers/apps/building-github-apps/rate-limits-for-github-apps#default-user-to-server-rate-limits-for-githubcom. 

Without a response caching layer, we can easily overshoot the above limit when we poll. To best avoid this scenario, we need to make [conditional request](https://docs.github.com/en/rest/overview/resources-in-the-rest-api?apiVersion=2022-11-28#conditional-requests) and setting the `If-None-Match` header to Etag value of the previous response.

I've created a [discussion thread](https://github.com/octokit/octokit.net/discussions/2643) and a [draft PR](https://github.com/octokit/octokit.net/pull/2648) for this

### SDK Version

_No response_

### API Version

_No response_

### Relevant log output

_No response_

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### PR DESCRIPTION
**Pull request by reny-gearset**
Resolves #2649

----

### Before the change?

* There's no way to cache GET responses, users can easily overshoot the Github API rate limit when polling.

### After the change?

* By implementing `IResponseCache` and setting it in the `ResponseCache` property in `GitHubClient`, we provide a way to cache GET responses and retain the API rate limit usage when its Etag matches. Specifically, we set the `If-None-Matched` header in the request with the non-null and non-empty Etag value from the cached response before sending it to Github.

### Other information

----

### Pull request checklist
- [x] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been reviewed and added / updated if needed (for bug fixes / features)
- [ ] Added the appropriate label for the given change

### Does this introduce a breaking change?

Please see our docs on [breaking changes](https://github.com/octokit/.github/blob/master/community/breaking_changes.md) to help!

- [ ] Yes (Please add the `Type: Breaking change` label)
- [x] No

If `Yes`, what's the impact:  

* N/A

### Pull request type

 
 

Please add the corresponding label for change this PR introduces:
- Bugfix: `Type: Bug`
- Feature/model/API additions: `Type: Feature`
- Updates to docs or samples: `Type: Documentation`
- Dependencies/code cleanup: `Type: Maintenance`

----

### CODE REVIEW

**Comment by reny-gearset** [comment]
@kfcampbell Thanks for sticking labels against the feature I raised - https://github.com/octokit/octokit.net/issues/2649 👍 

This is my first PR against an open source project, is there anything else I need to do to push this forward?

**Comment by nickfloyd** [comment]
Hey @reny-gearset, thank you for the contributions here! ❤️  | The item is on this [board](https://github.com/orgs/octokit/projects/10) to be reviewed - we'll let you know if anything comes up!

**Review by nickfloyd — APPROVED** [review]
Hey @reny-gearset, Thanks again for getting this knocked out.  This LGTM and should be good to merge once CI is ✅ ❤️

**Comment by nickfloyd** [comment]
Hey @reny-gearset , just a quick note about the sourcelink failure in the windows CI build.  It is unrelated to your change and is something we are working on.  Apologies for the noise.

**Comment by Revyn112** [comment]
@reny-gearset @nickfloyd any documentation or example on how to use this properly?

**Comment by Larusso** [comment]
As @Revyn112 stated. Is there some documentation what one needs to set there?

**Pull request merged**
