### PR TITLE
[fix] Fix handling for Streams in IConnection for raw content

### LINKED ISSUE #2789: [BUG]: NullReferenceException thrown using IConnection.GetRaw() for JSON content in Octokit 8.0.1
### What happened?

Calling `IConnection.GetRaw()` for an endpoint that responds with non-binary content (e.g. `application/json`) results in a `NullReferenceException` being thrown when updating to Octokit 8.0.1.

This appears to be [due to the changes](https://github.com/octokit/octokit.net/pull/2782/files#diff-2787e44423613b17ad12829a18645c782b89a5d4fa3cd945274e103c7167e77aR704-R713) in #2782 to handle large binary responses.

In the case where the response is not a `Stream` but instead is just a `string`, `response.Body as Stream` returns `null`, and then causes an exception here:

https://github.com/octokit/octokit.net/blob/0238092ca0370f2edc2ee27e31b7c6e8ba747280/Octokit/Http/Connection.cs#L724

Fix incoming shortly, but a workaround is to use `IConnection.GetRawStream()` and refactor calling code to deal with `Stream` instead of `byte[]`.

### Versions

8.0.1

### Relevant log output

```shell
System.NullReferenceException: Object reference not set to an instance of an object.
    at Octokit.Connection.StreamToByteArray(Stream stream) in /_/Octokit/Http/Connection.cs:line 724
    at Octokit.Connection.GetRaw(IRequest request) in /_/Octokit/Http/Connection.cs:line 704
    at MartinCostello.Costellobot.Pages.DeliveryModel.OnGet(Int64 id) in /_/src/Costellobot/Pages/Webhooks/Delivery.cshtml.cs:line 64
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### PR DESCRIPTION
**Pull request by martincostello**
Fix `NullReferenceException` if raw content was handled as a string rather than a stream by `HttpClientAdapter.BuildResponse()`.

I haven't added a test for this, but have validated that the apps that surfaced this issue are working when using a local build of Octokit including this change. If you can direct me to exactly where you'd like a test for this, I'll add one.

Resolves #2789

----

### Before the change?

* A `NullReferenceException` would be thrown.

### After the change?

* The call succeeds.

### Pull request checklist

- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been reviewed and added / updated if needed (for bug fixes / features)

### Does this introduce a breaking change?

- [ ] Yes
- [x] No

----

### CODE REVIEW

**Comment by martincostello** [comment]
Looks like this got closed by accident because I put the wrong `#` in the commit message for the other PR, and I can't re-open it.

**Comment by martincostello** [comment]
@nickfloyd Anything more you need from me to progress this fix?

**Comment by kfcampbell** [comment]
I do think it'd be possible to write a test for this case in `Octokit.Tests/Http/ConnectionTests.cs`, since the modified `GetRaw` is called by two public functions. Why don't we try doing so?

**Review by kfcampbell — APPROVED** [review]
Looks good, thank you!

**Pull request merged**
