### PR TITLE
IUserKeysClient.GetAll -> GetAllForCurrent()

### LINKED ISSUE #1136: IUserKeysClient.GetAll -> GetAllForCurrent()
https://developer.github.com/v3/users/keys/#list-your-public-keys

This is currently marked as obsolete on `ISshKeysClient.GetAllForCurrent()` but has not been ported over. Should be easy to port for both the `ISshKeysClient` and `IObservableSshKeysClient`.

### PR DESCRIPTION
**Pull request by M-Zuber**
Fixes #1136

### CODE REVIEW

**Comment by ryangribble** [comment]
Just me being pedantic, but now the method has been renamed, can we also please rename the unit test classes?

eg ```class TheGetAllMethod``` should now be ```class TheGetAllForCurrentMethod``` [here](https://github.com/M-Zuber/octokit.net/blob/fix%231136-IUserKeysClient.GetAll-GetAllForCurrent/Octokit.Tests/Reactive/ObservableUserKeysClientTests.cs#L11) and [here](https://github.com/M-Zuber/octokit.net/blob/fix%231136-IUserKeysClient.GetAll-GetAllForCurrent/Octokit.Tests/Clients/UserKeysClientTests.cs#L11)


Also AppVeyor build seems to be throwing a Code Analysis CA1024 error
> MSBUILD : error CA1024: Microsoft.Design : Change 'IUserKeysClient.GetAllForCurrent()' to a property if appropriate. [C:\projects\octokit-net\Octokit\Octokit.csproj]

Im not sure why ```GetAll```didnt trigger it but ```GetAllForCurrent```does, but you can suppress it (varoius examples through the codebase like [here](https://github.com/octokit/octokit.net/blob/5f2cc4cb4eb64163d9a9aa21751e3b6fa5ef6366/Octokit/Clients/Enterprise/IEnterpriseAdminStatsClient.cs#L21)

**Comment by shiftkey** [comment]
> can we also please rename the unit test classes?

:thumbsup:

> Im not sure why the method name `GetAll` didnt trigger it but `GetAllForCurrent`does, but you can suppress it 

I forget the exact reasons, but I gather FxCop just doesn't like methods without parameters (even though these return something more complex than a value)...

**Comment by ryangribble** [comment]
That doesn't explain why it didn't trip the error previously when called GetAll though does it?

**Comment by shiftkey** [comment]
@ryangribble it does not, no...

**Comment by ryangribble** [comment]
Hmm the build failures look like they couldn't talk to nuget.org at the time... 

I kicked off the Travis build again and that's now passed. Don't think I have access to do the same on Appveyor @Haacked @shiftkey

**Comment by shiftkey** [comment]
@ryangribble I'm on it

**Comment by shiftkey** [comment]
This all looks good to me. I'll let @ryangribble hit the big green button on it (it won't go out in v0.19, but that's a minor thing).

**Comment by ryangribble** [comment]
LGTM

**Comment by shiftkey** [comment]
release_notes: Renamed `IUserKeysClient.GetAll()` to `IUserKeysClient.GetAllForCurrent()`

**Pull request merged**
