### PR TITLE
Make NewRepository.HasIssues nullable as it's optional

### LINKED ISSUE #941: Unit tests that interact with issues on a repository are failing as issues are disabled
Example: `IssuesEventsClientTests.CanListEventInfoForAnIssue` throws `Octokit.ApiException : Issues are disabled for this repo`

### PR DESCRIPTION
**Pull request by alfhenrik**
Fixes #941

### CODE REVIEW

**Comment by shiftkey** [comment]
Kinda puzzled why we're only noticing this now. Whatever, the test suite did it's job :metal:

Thanks!

thumbsup-2

**Comment by alfhenrik** [comment]
I'm guessing we don't run the integration tests that often anymore as they take forever (aka timesout)?

**Comment by shiftkey** [comment]
I always run the integration tests before a release, so perhaps it's just a recent change...

**Comment by alfhenrik** [comment]
:+1:

**Pull request merged**
