### PR TITLE
Allow Path To Be An Empty String

### PR DESCRIPTION
**Pull request by thedillonb**
Addresses #1688

### CODE REVIEW

**Comment by thedillonb** [comment]
I figured the tests would fail. Regardless, just wanted to throw something up to get discussion moving on this. Either we allow empty strings to be passed as "paths" or we allow "/" to be passed and alter the logic following the `format` of the URL to prevent a double slash.

**Comment by ryangribble** [comment]
Whilst I'm not opposed to the change, were you aware that there are already overloads (that don't take a `path` parameter) which operate on the root directory of the repository?

https://github.com/octokit/octokit.net/blob/1e474f8556018ade97cc2d065aadb73aade74ca9/Octokit/Clients/IRepositoryContentsClient.cs#L48
https://github.com/octokit/octokit.net/blob/1e474f8556018ade97cc2d065aadb73aade74ca9/Octokit/Clients/IRepositoryContentsClient.cs#L58

https://github.com/octokit/octokit.net/blob/1e474f8556018ade97cc2d065aadb73aade74ca9/Octokit/Clients/IRepositoryContentsClient.cs#L96
https://github.com/octokit/octokit.net/blob/1e474f8556018ade97cc2d065aadb73aade74ca9/Octokit/Clients/IRepositoryContentsClient.cs#L108

**Comment by thedillonb** [comment]
@ryangribble well thats embarrassing. Good point. Didn't think to consider the other overloads. Those will do. I'll close the PR and issue. Thanks for pointing that out.

**Comment by ryangribble** [comment]
It obviuosly isn't disocverable though, given you didn't spot them...  

If we implicitly support an empty string via a different overload anyway, I dont have an issue with allowing the empty string to be explicitly passed in as `path`.  So I'd be happy to still take this PR if you got the tests working and updated the XmlDoc comment for the parameter to note that "Pass empty string for the root directory"

**Pull request closed without merging**
