### PR TITLE
Added ApiOption overloads to methods on I(Observable)RepositoryPagesClient

### LINKED ISSUE #1178: Add ApiOption overloads to methods on IRepositoryPagesClient
As part of completing #760 a number of overloads need to be added to the client interfaces.

As an example, this has been added to [`IReleasesClient`](https://github.com/octokit/octokit.net/commit/03ea83148995711fc47148489e2123e65f33bd82)and [`IObservableReleasesClient`](https://github.com/octokit/octokit.net/commit/aa3ce0db9210b778414e290af7f17c4a646bdeec).

The checklist for porting each method is:

- Add an overload for this method on `IRepositoryPagesClient` with a new parameter `ApiOptions`
- Implement the new method on the class which implements `IRepositoryPagesClient`
- Add an overload for this method on `IObservableRepositoryPagesClient` with a new parameter `ApiOptions`
- Implement the new method on the class which implements `IObservableRepositoryPagesClient`

This needs to be done for each of these methods:

- [ ] `Task<IReadOnlyList<PagesBuild>> GetAll(String owner, String repositoryName)`

### PR DESCRIPTION
**Pull request by shiftkey**
Fixes #1178

Supersedes #1213 and addresses merge conflict

### CODE REVIEW

**Comment by shiftkey** [comment]
@ryangribble can I get a :thumbsup: here before I merge this in?

**Comment by ryangribble** [comment]
Looks pretty good, although I didn't see integration tests that actually test the pagination... Is that because there isn't a suitable repo that has enough responses?

**Comment by shiftkey** [comment]
@ryangribble it's because anything related to Pages requires the account to be an administrator of the repository: https://github.com/octokit/octokit.net/issues/1263

**Comment by ryangribble** [comment]
Yeah I saw the existing test was skipped, I guess I was just questioning whether there should still be the pagination test written, then also skipped? 

The code changes look fine though so 👍 if you aren't concerned about the missing test

**Comment by shiftkey** [comment]
@ryangribble good point. I'll add the test so we don't forget it and then close this out...

**Pull request merged**
