### PR TITLE
[WIP] when a merge fails, raise more specific exceptions

### LINKED ISSUE #373: When you try to merge a branch that isn't mergeable, get a better exception
As per http://developer.github.com/v3/pulls/#merge-a-pull-request-merge-button the API returns a `405 Method not allowed` when the PR is set as `mergeable: false`

We should raise a specific exception here, rather than the generic API exception...

### PR DESCRIPTION
**Pull request by shiftkey**
- [ ] update xml-docs to call out exceptions
- [ ] integration tests

Fixes #373

See [the docs](https://developer.github.com/v3/pulls/#merge-a-pull-request-merge-button) for more details.

### CODE REVIEW

**Comment by OlegKleyman** [comment]
test

**Comment by elbaloo** [comment]
Want some help here? What is missing?

**Comment by shiftkey** [comment]
@elbaloo i'm not sure, probably just some docs (oh, and to merge master in).

**Comment by elbaloo** [comment]
I'm trying to figure out why these two new exceptions don't inherit from ApiException... isn't it desirable? Noticed it while working on the integration tests since they don't have ApiError member.

**Comment by elbaloo** [comment]
Worked a bit on this on #931.

No idea where to document this tho.

**Comment by Haacked** [comment]
Yeah, they probably should inherit from `ApiException`.

**Comment by shiftkey** [comment]
Closing this in favour of #934

**Pull request closed without merging**
