### PR TITLE
Refactors GitHubSerializerStrategy to be thread-safe (#1683)

### LINKED ISSUE #1683: Deserialization crash with duplicate dictionary key in Events api
Not sure if there is too much we can do about this but I thought I would raise it, as I sporadically run into this error.  

This is targetting GitHub Enterprise 2.8.7 using the latest  (0.26) Octokit.net

The following line of code
``` csharp
var events = await this.GitHubClient.Issue.Events.GetAllForIssue(owner, repository, issue.Number);
```

Sometimes throws the following exception inside Octokit, but when re-running against the same repo/issue it does not occur again, thus it is proving hard to track down!  I also ran a test in a loop overnight and still could not get a repro!  I really want to see the json response from the server to see if there actually is a duplicate field in the response or whether it is some kind of timing issue with the internal deserialization logic

```
System.ArgumentException : An item with the same key has already been added.
   at System.ThrowHelper.ThrowArgumentException(ExceptionResource resource)
   at System.Collections.Generic.Dictionary`2.Insert(TKey key, TValue value, Boolean add)
   at System.Collections.Generic.Dictionary`2.Add(TKey key, TValue value)
   at Octokit.Internal.SimpleJsonSerializer.GitHubSerializerStrategy.DeserializeObject(Object value, Type type) in D:\repos\octokit.net\Octokit\Http\SimpleJsonSerializer.cs:line 126
   at Octokit.PocoJsonSerializerStrategy.DeserializeObject(Object value, Type type) in D:\repos\octokit.net\Octokit\SimpleJson.cs:line 1478
   at Octokit.Internal.SimpleJsonSerializer.GitHubSerializerStrategy.DeserializeObject(Object value, Type type) in D:\repos\octokit.net\Octokit\Http\SimpleJsonSerializer.cs:line 165
   at Octokit.PocoJsonSerializerStrategy.DeserializeObject(Object value, Type type) in D:\repos\octokit.net\Octokit\SimpleJson.cs:line 1505
   at Octokit.Internal.SimpleJsonSerializer.GitHubSerializerStrategy.DeserializeObject(Object value, Type type) in D:\repos\octokit.net\Octokit\Http\SimpleJsonSerializer.cs:line 165
   at Octokit.SimpleJson.DeserializeObject(String json, Type type, IJsonSerializerStrategy jsonSerializerStrategy) in D:\repos\octokit.net\Octokit\SimpleJson.cs:line 583
   at Octokit.SimpleJson.DeserializeObject[T](String json, IJsonSerializerStrategy jsonSerializerStrategy) in D:\repos\octokit.net\Octokit\SimpleJson.cs:line 595
   at Octokit.Internal.SimpleJsonSerializer.Deserialize[T](String json) in D:\repos\octokit.net\Octokit\Http\SimpleJsonSerializer.cs:line 21
   at Octokit.Internal.JsonHttpPipeline.DeserializeResponse[T](IResponse response) in D:\repos\octokit.net\Octokit\Http\JsonHttpPipeline.cs:line 62
   at Octokit.Connection.<Run>d__54`1.MoveNext() in D:\repos\octokit.net\Octokit\Http\Connection.cs:line 574
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   at Octokit.ApiConnection.<GetPage>d__41`1.MoveNext() in D:\repos\octokit.net\Octokit\Http\ApiConnection.cs:line 589
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   at Octokit.ApiConnection.<>c__DisplayClass17_0`1.<<GetAll>b__0>d.MoveNext() in D:\repos\octokit.net\Octokit\Http\ApiConnection.cs:line 197
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   at Octokit.ApiPagination.<GetAllPages>d__0`1.MoveNext() in D:\repos\octokit.net\Octokit\Clients\ApiPagination.cs:line 25
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
```

### PR DESCRIPTION
**Pull request by daveaglick**
Fixes #1683 

I think this is good to go - passes tests at least. Might want to double-check the integration tests though - I had a few problems with those that appeared unrelated to this change.

### CODE REVIEW

**Comment by ryangribble** [comment]
Thanks!  I will run this through integration tests locally tonight, I may even look to add an integration test that uses a `Task.WhenAll` concurrency to reproduce the problem and confirm this fixes it :+1:

**Comment by ryangribble** [comment]
Really struggling to produce a repro of the issue, so i can test the fix 😬 

If you have any repro code, let me know @daveaglick

**Comment by daveaglick** [comment]
I don’t, same problem - it was happening about 1 in 20 runs in my project where I `Task.WhenAll()` the projects endpoint for around 40 projects. It hasn’t happened since switching to this build, but that could just be because of luck. It’s so intermittent, it’s hard to tell.

Let me see if I can come up with anything - maybe by targeting just at the cache and pumping in hundreds of types or something I can get it to repro.

**Comment by ryangribble** [comment]
I've run all the integration tests and am happy with this change.  It would be nice to have a repro test but I've been throwing all sorts of parallel things together, using mocked responses, just the enum deserializer, even running against the actual github API and havent even managed to trigger the failure condition (before this fix is applied).

Unless you've come up with anything @daveaglick I think it's going to be a YOLO merge for this one 😝

**Comment by daveaglick** [comment]
I tried over the weekend and couldn't come up with anything reliable. I did get it to fail a few times under observation, but nothing that would hold up in a test suite.

**Comment by ryangribble** [comment]
Cool well given I've run the integration tests succesfully locally, and neither of us are able to get a reliably reproducible scenario, Im happy to merge this :+1:

Thanks heaps for contributing this fix @daveaglick !

~[LGTM](https://media0.giphy.com/media/3o6Zt6KHxJTbXCnSvu/giphy.gif?cid=e1bb72ff5a71b1067631584f735f1d1a)

**Comment by daveaglick** [comment]
👍

**Comment by ryangribble** [comment]
release_notes: Using the same `GitHubClient` instance from multiple threads in parallel will no longer throw occasional exceptions, after making the `GitHubSerializerStrategy` internals thread-safe

**Pull request merged**
