### PR TITLE
Add ApiOption overloads to methods on Assignees API

### LINKED ISSUE #1148: Add ApiOption overloads to methods on IAssigneesClient
As part of completing #760 a number of overloads need to be added to the client interfaces.

As an example, this has been added to [`IReleasesClient`](https://github.com/octokit/octokit.net/commit/03ea83148995711fc47148489e2123e65f33bd82)and [`IObservableReleasesClient`](https://github.com/octokit/octokit.net/commit/aa3ce0db9210b778414e290af7f17c4a646bdeec).

The checklist for porting each method is:

- Add an overload for this method on `IAssigneesClient` with a new parameter `ApiOptions`
- Implement the new method on the class which implements `IAssigneesClient`
- Add an overload for this method on `IObservableAssigneesClient` with a new parameter `ApiOptions`
- Implement the new method on the class which implements `IObservableAssigneesClient`

This needs to be done for each of these methods:

- [ ] `Task<IReadOnlyList<User>> GetAllForRepository(String owner, String name)`

### PR DESCRIPTION
**Pull request by devkhan**
Fixes #1148.

I have added the necessary overloads and corresponding tests. But one test is failing: 

`AssigneesClientTests+TheGetForRepositoryMethod.RequestsCorrectUrl()`

[Here](https://github.com/octokit/octokit.net/pull/1186/files#diff-a41fcaa8133dfe3db5942c64690de5adR24) are the changes I made. All other tests including integration tests are passing.

/cc @shiftkey

### CODE REVIEW

**Comment by ryangribble** [comment]
Hi @devkhan 

We'll typically hold off from reviewing PR's until the CI builds are passing... You should be able to click through and see what caused the failures :grinning:

**Comment by devkhan** [comment]
@ryangribble The CI builds are passing now. Review and merge whenever you want to. :smile:

**Comment by shiftkey** [comment]
Integration tests passing, no issues with the code - this is just great! Thanks @devkhan!

**Comment by devkhan** [comment]
@shiftkey Should I now start the bulk changes for Pagination Support?

**Comment by shiftkey** [comment]
@devkhan let's not rush through these - we're discussing some API changes in #1190, and doing reviews per-client is easier for us to ensure we don't miss anything...

**Comment by devkhan** [comment]
@shiftkey Okay, as you say, but may be we can try a few similar ones?

**Pull request merged**
