### PR TITLE
Disposable repositories

### PR DESCRIPTION
**Pull request by willsb**
This solves Issue #655 

I created the structure and refactored the `RepositoriesClientTests` as a way to test what the new syntax looks like. It looks good, but having to write  `var createdRepository = context.Repository;` every  time is kinda boring, I wonder if this can be simplified somehow.

If this looks good I'll refactor the other test classes to use the new syntax as well

____
Those use the same repository for multiple tests, so they won't have the nice `using` syntax. I'll change them for consistency, though

 - [x] AssigneesClientTests.cs
 - [x] BlobClientTests.cs
 - [x] CommitsClientTests.cs
 - [x] CommitStatusClientTests.cs
 - [x] DeploymentsClientTests.cs
 - [x] DeploymentStatusClientTests.cs
 - [x] IssuesClientTests.cs
 - [x] IssuesEventsClientTests.cs
 - [x] IssuesLabelsClientTests.cs
 - [x] MergingClientTests.cs
 - [x] MilestonesClientTests.cs
 - [x] PullRequestReviewCommentsClientTests.cs
 - [x] PullRequestsClientTests.cs
 - [x] ReferencesClientTests.cs
 - [x] ReleasesClientTests.cs
 - [x] RepositoryCommitsClientTests.cs
 - [x] RepositoryDeployKeysClientTests.cs
 - [x] TreeClientTests.cs
 - [x] ObservableIssuesClientTests.cs

`RepositoryHooksClientTests`, however, uses the `RepositoriesHooksFixture` class, I wonder if this shoud be replaced to use the new context approach or not

### CODE REVIEW

**Comment by Haacked** [comment]
Looks good! Feel free to continue.

**Comment by willsb** [comment]
[ ] AssigneesClientTests.cs
[ ] BlobClientTests.cs
[ ] BranchesClientTests.cs
[ ] CommitsClientTests.cs
[ ] CommitStatusClientTests.cs
[ ] DeploymentsClientTests.cs
[ ] DeploymentStatusClientTests.cs
[ ] IssuesClientTests.cs
[ ] IssuesEventsClientTests.cs
[ ] IssuesLabelsClientTests.cs
[ ] MergingClientTests.cs
[ ] MilestonesClientTests.cs
[ ] PullRequestReviewCommentsClientTests.cs
[ ] PullRequestsClientTests.cs
[ ] ReferencesClientTests.cs
[ ] ReleasesClientTests.cs
[ ] RepositoriesClientTests.cs
[ ] RepositoryCommitsClientTests.cs
[ ] RepositoryDeployKeysClientTests.cs
[ ] RepositoryHooksClientTests.cs
[ ] TreeClientTests.cs
[ ] RepositoriesHooksFixture.cs
[ ] ObservableIssuesClientTests.cs

**Comment by willsb** [comment]
All set! If anything else needs to be done, just let me know once this gets reviewed, @Haacked

**Comment by Haacked** [comment]
Looks good! :sparkles:

**Pull request merged**
