### PR TITLE
Obsolete assert ex.throws

### PR DESCRIPTION
**Pull request by M-Zuber**
Clean up the tests in order to comply with #782 

- [x] `OctoKit.Tests`
  - [x] `Clients`
  - [x] `Helpers`
  - [x] `Http`
  - [x] `Reactive`
- [x] `Octokit.Tests.Integration`
  - [x] `Clients`

### CODE REVIEW

**Comment by M-Zuber** [comment]
As can be seen in some of the commits, a number of expected exception types had to be changed. Please let me know if there is an issue with this.

**Comment by shiftkey** [comment]
> As can be seen in some of the commits, a number of expected exception types had to be changed. 

This is likely due to the fact we don't assert the exception type in that helper method I wrote. Oops.

**Comment by M-Zuber** [comment]
@shiftkey for the `Reactive` tests when I remove the inner `async / await`, it complains that it needs an explicit conversion to `Task`.
Which is the better option:
```c#
await Assert.ThrowsAsync<ArgumentNullException>(() => (Task)client.Create(null, "name", new NewBlob()));
//or leave the inner async/await
await Assert.ThrowsAsync<ArgumentNullException>(async () => await client.Create(null, "name", new NewBlob()));

```

**Comment by shiftkey** [comment]
@M-Zuber try this:

```csharp
await Assert.ThrowsAsync<ArgumentNullException>(() => client.Create(null, "name", new NewBlob()).ToTask());
```

**Comment by M-Zuber** [comment]
@shiftkey If the final `AppVeyor` builds succeeds then this is pretty much done.

One thing that I did not do is places where the call was not awaited where left that way after updating the method call.

**Comment by M-Zuber** [comment]
@shiftkey

**Comment by shiftkey** [comment]
Thanks @M-Zuber!

**Pull request merged**
