### PR TITLE
bugfix - PUT should have a payload for Mark as Read

### LINKED ISSUE #1578: Notifications.MarkAsRead() throws Octokit.ApiException
The method ` client.Activity.Notifications.MarkAsRead();` is throwing an exception. 

Type: Octokit.ApiException
HttpResponse Body:
{"message":"Problems parsing JSON","documentation_url":"https://developer.github.com/v3"}

### PR DESCRIPTION
**Pull request by shiftkey**
Fixes #1578

### CODE REVIEW

**Comment by ryangribble** [comment]
The `MarkAsReadForRepository()` methods suffer from the same problem.  I wrote some integration tests and found they also are failing.

Pushing up fixes now...

**Comment by ryangribble** [comment]
PS, there are also a handful of other API clients where `PUT` is called without providing a body.  

I'll do some poking to see if this also causes HTTP 400 errors and follow up on a separate PR if fixes are required

**Comment by ryangribble** [comment]
If someone can give this a quick 👀 I'll hit the button

**Comment by shiftkey** [comment]
:shipit:

**Comment by ryangribble** [comment]
release_notes: Fix `NotificationsClient.MarkAsRead()` exception by specifying a payload body in the `PUT` request

**Pull request merged**
