### PR TITLE
[WIP] Added support for Repository Topics, unit tests to be added

### PR DESCRIPTION
**Pull request by MuazOthman**
This pull request is addressing #1707

- [x] Add `Topics` field to `Repository` response class
- [x] Specify new preview header on all calls that return `Repository` responses
- [x] Update unit tests to pass after adding preview header
- [x] New API: List all Topics
- [ ] Write unit tests for List all Topics (done partially)
- [x] New API: Replace all Topics
- [ ] Write unit tests for Replace all Topics
- [ ] Add `string Topic` field to `SearchRepositoriesRequest` and format search parameters accordingly
- [ ] Add `Range Topics` field to `SearchRepositoriesRequest` and format search parameters accordingly

### CODE REVIEW

**Comment by ryangribble** [comment]
Hi @MuazOthman just wondering if you still want this PR kept open?

**Comment by MuazOthman** [comment]
@ryangribble sorry for the late response, it's crunch time at work these days! Please keep this open if possible, I'll try to get back to it as soon as I get the chance.

**Comment by jonnii** [comment]
What's left to get this over the line? Anything I can do to help?

**Comment by MuazOthman** [comment]
That would be great! The checklist above can provide guidance to what's still to do.
I can add you to my repo if you want and you're welcome to pick it up there.

**Comment by MuazOthman** [comment]
@jonnii I just invited you, thanks for offering to help

**Comment by jozefizso** [comment]
Is this being working on? Do you need help with getting this implementation done?

**Comment by ryangribble** [comment]
Hi @jozefizso it would be awesome if you wanted to pick this one up!

**Comment by jozefizso** [comment]
sure

**Comment by exavian** [comment]
@MuazOthman Are you still keeping an eye on this? I grabbed the changes from [this PR](https://github.com/MuazOthman/octokit.net/pull/1) and have put in some work.

**Comment by KeesCBakker** [comment]
Any progress on this topic?

**Comment by SeanKilleen** [comment]
Hey all,

FYI, I have a PR (#2246) that supersedes this to tackle #1707. 

If you worked on this pull request, I'd welcome your input/review over at #2246.

**Comment by shiftkey** [comment]
Closing this out in favour of #2246, which should be out in the next release

**Pull request closed without merging**
