### PR TITLE
Dev put release on iRepository from iGitHub client

### PR DESCRIPTION
**Pull request by RobPethick**
Fixes #1047

### CODE REVIEW

**Comment by RobPethick** [comment]
@shiftkey any idea why this is failing? It looks like it is complaining about building Tests-Portable but it seems to build locally just fine for me have I missed something?

**Comment by naveensrinivasan** [comment]
@RobPethick @shiftkey  Nothing is wrong. It just timed out on linux and but was successful on OSX. We are good.

**Comment by RobPethick** [comment]
@naveensrinivasan Ah I thought it might be something like that thanks for confirming

**Comment by shiftkey** [comment]
I have zero issues with this PR. Thanks for the effort @RobPethick!

**Pull request merged**
