### PR TITLE
Splitting out the misc client into separate clients as per current documentation

### PR DESCRIPTION
**Pull request by JonruAlveus**
Splitting out Miscellaneous client into new clients.

1. Split clients and interfaces
2. Redirect misc client to new interfaces
3. Obsolete methods with descriptions
4. Repeat for Observable
5. Duplicate unit tests
6. Duplicate integration tests

### CODE REVIEW

**Comment by JonruAlveus** [comment]
@SeanKilleen @timrogers @nickfloyd I've made a start, let me know if there's anything glaring (the build will likely fail but I've gotta go!).

**Comment by JonruAlveus** [comment]
All done. Emojis and Meta endpoints didn't work before and don't work now, that can be dealt with separately. I believe Emojis already has a PR but might need to be done again.

**Comment by SeanKilleen** [comment]
@JonruAlveus probably makes sense to file an additional issue about emoji and meta endpoints not working and why. 👍 Nice work on this!

**Comment by JonruAlveus** [comment]
Thanks @SeanKilleen, I have both raised issues and PRs :)

**Review by nickfloyd — APPROVED** [review]
Thanks for getting this knocked out! 🎉

**Comment by nickfloyd** [comment]
release_notes: Splits out the misc client into separate clients as per current documentation

**Pull request merged**
