### PR TITLE
Creates constructors for all Models.Response.

### PR DESCRIPTION
**Pull request by Zoltu**
Resolves https://github.com/octokit/octokit.net/issues/677.

There are a lot of code analysis warnings about URIs as Strings.  Let me know what the preferred way to resolve this is and I'll apply the fix across the board in this PR.

Also, this doesn't build currently due to the usage of obsolete properties.  An example is User.cs which has an Obsolete GravatarId.  The constructor assigns it, which causes an obsolete usage warning at compile time.  What is the preferred way to deal with this situation?

### CODE REVIEW

**Comment by Haacked** [comment]
> There are a lot of code analysis warnings about URIs as Strings. Let me know what the preferred way to resolve this is and I'll apply the fix across the board in this PR.

My inclination is to pass in `Uri` and call `ToString()` on them when setting the property. These constructors aren't used in normal usage. They're primarily there for testing and in the rare case someone needs to override a behavior and explicitly create these types. In those cases, why not require a URI. @shiftkey any thoughts?

I think we should get rid of the obsolete properties in this PR. It's about time. :smile:

**Comment by shiftkey** [comment]
> In those cases, why not require a URI. @shiftkey any thoughts?

The rule is basically:

> A type declares a method with a string parameter whose name contains "uri", "Uri", "urn", "Urn", "url", or "Url" and the type does not declare a corresponding overload that takes a System.Uri parameter.

My first instinct was "Could we mute this rule?" And yes, adding this element to `Octokit.ruleset` kills off these warnings: `<Rule Id="CA1054" Action="None" />`

So that's what I'd favour for this - as long as the `ctor`s are `protected`, whatever.  

> I think we should get rid of the obsolete properties in this PR. 

:thumbsup:

**Comment by Haacked** [comment]
> So that's what I'd favour for this - as long as the ctors are protected, whatever.

Most of the ctors are `public`. The point of them is to allow people to create these instances without having to subclass them.

**Comment by Zoltu** [comment]
I removed the obsolete properties.

For the warning about URL as a string, I went with the rule suggested by @shiftkey since there wasn't an agreement in this thread and it was by far the easier solution.

I moved all of the constructors to above the properties per http://www.stylecop.com/docs/SA1201.html since there doesn't appear to be a hard and fast standard and a good portion of the response models that already had constructors followed this style.

I created default constructors for all of the response models since it appears SimpleJson needs them to work correctly (tests failed without).

Finally, I changed a couple (maybe it ended up only being one) response model from public setter to private setter to match all of the others.

**Comment by Haacked** [comment]
This is really great! It's tedious work and very much appreciated!


selfie-0

**Comment by Haacked** [comment]
BTW, now that we have proper ctors, we don't need all the model properties to have `protected` setters. Probably best to make them `private`.

**Pull request merged**
