### PR TITLE
VS2015 migration

### PR DESCRIPTION
**Pull request by shiftkey**
- [x] can build under VS2015 locally
- [x] can build on AppVeyor
- [x] `netcore45` -> `netcore451` target it any more
- [x] test and verify standard version can build and test this
- [x] docs
- [x] CI back to green
- [x] run integration tests
- [x] test preview package in a Store app

### CODE REVIEW

**Comment by Haacked** [comment]
Nice! I know @Eilon was just asking me if we could switch Octokit.net to VS 2015. I think he even offered to help. 😛

**Comment by shiftkey** [comment]
@Haacked it looks like the xml-doc warnings are causing the build to fail incorrectly. I *really* don't want to go through and triage it all, but maybe I have to?

**Comment by Haacked** [comment]
I would set the doc warnings as warnings and not errors and assign it to me to fix later.

**Comment by shiftkey** [comment]
@Haacked good point, I'll do that now and see if the build is happy with that...

**Comment by Eilon** [comment]
Looks :shipit: to me!

**Comment by naveensrinivasan** [comment]
:+1:

**Pull request merged**
