### PR TITLE
Added Organization to code search (#1671)

### LINKED ISSUE #1671: Search Code should allow filtering by organization / repository
Currently only the User filter is allowed
But in github's documentation it's possible to search by Organization or Repository (https://help.github.com/articles/searching-code/#search-within-a-users-or-organizations-repositories)

The SearchCodeRequest should include extra filters based on those fields to provide this functionality

### PR DESCRIPTION
**Pull request by sepharg**
Fixes #1671 
new field allows filtering by organization

### CODE REVIEW

**Comment by ryangribble** [comment]
Thanks @sepharg!

Could you please add an integration test that verifies all returned repos are from the requested organization?

Are there any other missing filter options on code search that we should implement at the same time?

**Comment by sepharg** [comment]
hi @ryangribble sure, I´ll add an integration test. As far as I´m aware that was the only missing field

**Comment by sepharg** [comment]
@ryangribble everything good to go if you think it's all fine

**Comment by ryangribble** [comment]
Thanks @sepharg , I ran the integration test but it failed due to specifying a blank search term and using the incorrect owner Url 😀   But I've pushed a couple of fixes to your branch and its all ✅ now

I'll just wait for AppVeyor and TravisCI to give the go ahead then I'll be right to merge it!

**Comment by ryangribble** [comment]
release_notes: Implement `Organization` filter in `ISearchClient.SearchCode()`

**Comment by ryangribble** [comment]
Awesome stuff @sepharg thanks heaps for the contribution!  Hope to see more from you in the future 😀

**Comment by sepharg** [comment]
@ryangribble sorry about the tests, it was pretty hard to have them running locally and I couldn´t find a way to run my test in isolation, then i saw the build green and thought it must have run ok
anyway great collaboration, and I certainly hope to help more in the future! :)

**Comment by ryangribble** [comment]
No worries, due to how many integration tests we have, we cant run them from AppVeyor or Travis at the moment!  I will pull down the branch and run them locally before merging a PR.

What IDE are you using?  To run individual tests we would normally use the Test Runner in Visual Studio 2017.  There is also some setup required which is covered in the CONTRIBUTING guide.  If you do want any help to get your environment setup, drop into our gitter chat and we can help you

Thanks again for the PR!

**Comment by sepharg** [comment]
I'm using Visual Studio 2017 with Resharper. I followed the guide and tried to run the test but I had issues, next time I'll drop a message in the chat so that I can get it running locally. 
No worries, happy to be of help and contribute to the community!

**Pull request merged**
