### PR TITLE
Fix for Repository.Content.GetAllContents working at the root of the repo

### LINKED ISSUE #800: client.Repository.Content.GetAllContents for root not currently possible.
Task<IReadOnlyList<RepositoryContent>> GetAllContents(string owner, string name, string path);
Will currently only work with subdirectories ie:
`client.Repository.Content.GetAllContents("octokit", "octokit.net", "Octokit")` returns 18 items.
However
`client.Repository.Content.GetAllContents("octokit", "octokit.net", "")` Throws a ArgumentException("String cannot be empty", name)

For a quick fixed I hacked GetAllContents as follows locally but a better option is probably needed.

```cs
public async Task<IReadOnlyList<RepositoryContent>> GetAllContents(string owner, string name, string path)
        {
            Ensure.ArgumentNotNullOrEmptyString(owner, "owner");
            Ensure.ArgumentNotNullOrEmptyString(name, "name");
            //Ensure.ArgumentNotNullOrEmptyString(path, "path");
            System.Uri url;
            if (string.IsNullOrEmpty(path))
            {
                url = ApiUrls.RepositoryContent(owner, name);
            }
            else
            {
                url = ApiUrls.RepositoryContent(owner, name, path);
            }
            return await ApiConnection.GetAll<RepositoryContent>(url);
        }
```

### PR DESCRIPTION
**Pull request by shiftkey**
Fixes #800 

There's some changes in #959 unrelated to the problem reported in #800 - and an outstanding merge conflict - so I've pulled in just those commits, cleaned up the xml-docs issue, and pushed this to verify the fix.

 - [x] there's some `async/await` i think i can clean up here?
 - [x] pretty sure this is a breaking change - document this for the release?

cc @naveensrinivasan to ensure I didn't miss any commits

### CODE REVIEW

**Comment by naveensrinivasan** [comment]
@shiftkey  Thanks for pulling this in.

**Comment by shiftkey** [comment]
Ready for review

**Comment by shiftkey** [comment]
Actually, given #959 went through a review by myself and @haacked I'm just going to merge this in so I can get it into the next release...

**Comment by jamesqo** [comment]
I just ran into this error. For some reason, it looks like the argument validation was added back during https://github.com/octokit/octokit.net/pull/1348 and no one took notice.

**Pull request merged**
