### PR TITLE
Add `stale` check conclusion

### PR DESCRIPTION
**Pull request by BenEmdon**
Hey Dotnet SDK team 👋 

I work on the team which maintains checks at GitHub and I wanted to add this conclusion ahead of release. This check conclusion will be fully documented on release.

I would also like to note that we could add new check/status states at any time, since adding states would be an additive change. The client-side logic should reflect this in some way so that new states don't break integrators systems.

### CODE REVIEW

**Comment by shiftkey** [comment]
> The client-side logic should reflect this in some way so that new states don't break integrators systems.

Yep, for states that we don't know they'll fallback to `null` until we add them.

**Comment by BenEmdon** [comment]
> @shiftkey Yep, for states that we don't know they'll fallback to `null` until we add them.

Good to know! Apologies for my wrong assumption, I am not accustomed to the codebase 😅

**Comment by shiftkey** [comment]
@BenEmdon no problem - totally understandable!

**Comment by shiftkey** [comment]
release_notes: Add `CheckConclusion.Stale` value to `Conclusion` property for `CheckSuite` and `CheckRun`

**Pull request merged**
