### PR TITLE
Add convention test to ensure pagination methods meet naming conventions

### LINKED ISSUE #767: IEventsClient doesn't follow naming conventions
These methods all paginate - as per #760 they should be renamed to start with `GetAll`:

 - `IEventsClient.GetUserReceived`  -> `GetAllReceived`
 - `IEventsClient.GetUserReceivedPublic`  -> `GetAllReceivedPublic`
 - `IEventsClient.GetUserPerformed` -> `GetAllPerformed`
 - `IEventsClient.GetUserPerformedPublic` -> `GetAllPerformedPublic`
 - `IEventsClient.GetForAnOrganization` -> `GetAllForOrganization`

You might have even better suggestions.

### PR DESCRIPTION
**Pull request by alfhenrik**
- [x] Convention Test
- [x] Update all methods that failed the convention test
- [x] Breaking changes all around :neckbeard: 
- ~~[ ] [:cherries: on top] Convention test to include Observable clients~~...this would be caught in the `SyncObservableInterfaces` test though...~~so might not be urgently needed~~.

Fixes #767 #768 #769 #770 #772

### CODE REVIEW

**Comment by alfhenrik** [comment]
Nice little sample of what errors for this convention test will look like :grimacing: https://ci.appveyor.com/project/Haacked15676/octokit-net/build/1.0.847/tests

**Comment by alfhenrik** [comment]
As long as AppVeyor gives me a nice green :white_check_mark: this is ready for review

cc @shiftkey

**Comment by shiftkey** [comment]
>  this would be caught in the SyncObservableInterfaces test though...so might not be urgently needed.

That was my thinking on this too. I think we can drop this unless there's another reason to test the observable interfaces explicitly...

**Comment by alfhenrik** [comment]
Dropped :smiley:

**Comment by shiftkey** [comment]
Thanks heaps for working through this!

**Pull request merged**
