### PR TITLE
Making Encodedcontent public #861

### PR DESCRIPTION
**Pull request by naveensrinivasan**
Making `EncodedContent` public to get the raw bytes of a file. #861

### CODE REVIEW

**Comment by Haacked** [comment]
That looks like a legit failure. We have some unit tests that check that models follow our conventions.

**Comment by alfhenrik** [comment]
Yea, needs to have the `setter` as protected... :)

**Comment by naveensrinivasan** [comment]
Thanks fixed that!. It is failing again in the `StopsMakingNewRequestsWhenTakeIsFulfilled`

**Comment by Haacked** [comment]
> Thanks fixed that!. It is failing again in the `StopsMakingNewRequestsWhenTakeIsFulfilled`

I restarted the build. I haven't had time to look into why that test fails sometimes. It's worrying.

**Comment by Haacked** [comment]
Looks good to me!

**Pull request merged**
