### PR TITLE
ye old build script story

### LINKED ISSUE #899: Polish up the NuGet Package Publishing or Deployment Story
Our guidelines for publishing packages are outdated. Also, when you try and do it manually, we run into [this bug](https://github.com/ctaggart/SourceLink/issues/58) which tells you to clone Octokit.net like so: `git clone https://github.com/octokit/octokit.net.git -c core.autocrlf=input`.

We should figure out an approach that is more automated and actually works. :smile:

### PR DESCRIPTION
**Pull request by shiftkey**
First off, sorry for letting the deployment instructions get out of date and of course something would come up as soon as I go on holiday :cry:

Fixes #899 

Here's me brain-dumping and scripting stuff out, so it won't happen again:

- [x] `script/bootstrap` to setup your repository right
- [x] `script/build` to just build and test
- [x] `script/package` to ensure you can correctly generate packages
- [x] refactor pre-requisite installation into common function for use in both `build` and `package`
- [x] resolve missing dependency for SourceLink (found on multiple environments)
- [x] update and centralize docs
- [ ] the normalizing of the repo seems to fail - why?

There's lots of potential headaches here with running the integration tests (exhausting API limits, hitting anti-spam measures, etc) so that's a lower priority for me right now.

I'll also leave automating the releases in #905 to @naveensrinivasan

### CODE REVIEW

**Comment by shiftkey** [comment]
Blocked on https://github.com/ctaggart/SourceLink/issues/106

**Comment by shiftkey** [comment]
Was able to workaround the SourceLink issue in https://github.com/shiftkey/octokit.net/commit/e389f08153d19cc0a9902fff9fc671cdce01f765 with a bit of F# munging. Now to tidy up everything else.

**Comment by ctaggart** [comment]
Me too! I'll take a look this week.

**Comment by shiftkey** [comment]
@ctaggart thanks for looking into it!

**Comment by shiftkey** [comment]
Just did a run-through of this process with a fresh clone, and here's the process:

1. `git clone ...` - note that the `core.autocrlf` thing isn't set because it's an implementation detail
2. `./build` as per the README - I've kept this script around but it now shells out to `bootstrap`, `build` and then `test` scripts.

So the big headache we had previous was that `SourceLink` required the `core.autocrlf` setting to be a certain value - otherwise shit just breaks. Here's what happens now as part of the `bootstrap` step:

```
> ./script/bootstrap
WARNING: core.autocrlf not configured correctly for repository
You will have problems with generate the source indexing during packaging.

But guess what? I can set this up for you!
This will overwrite any changes in your local working tree.
If you want to continue, press Y.
Press any other key to skip this.

Would you like me to configure this: Y
Done!
Installing dependencies...

Package "FAKE.Core" is already installed.
Package "xunit.runner.console" is already installed.
Package "SourceLink.Fake" is already installed.
Package "FSharp.Data" is already installed.
```

This means less hunting around in docs for setting this value (and then remembering to run some other git commands afterwards). We can also guard against this when packaging:

```
> ./script/package
C:\Users\shiftkey\Documents\GitHub\test\octokit.net\script\package.ps1 : core.autocrlf not configured correctly for
repository
At line:1 char:1
+ ./script/package
+ ~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Write-Error], WriteErrorException
    + FullyQualifiedErrorId : Microsoft.PowerShell.Commands.WriteErrorException,package.ps1

C:\Users\shiftkey\Documents\GitHub\test\octokit.net\script\package.ps1 : Run ./script/bootstrap to set correct state
for packaging
At line:1 char:1
+ ./script/package
+ ~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Write-Error], WriteErrorException
    + FullyQualifiedErrorId : Microsoft.PowerShell.Commands.WriteErrorException,package.ps1
```

Could probably be a bit more friendly. But anyway, after doing your `./build` it's a one-liner to package things up:

```
C:\Users\shiftkey\Documents\GitHub\test\octokit.net [some-better-build-scripts]> ./script/package

Patching FAKE app.config to workaround assembly binding issue...

Creating packages...

Building project with version: LocalBuild
Shortened DependencyGraph for Target CreatePackages:
<== CreatePackages
   <== SourceLink
   <== CreateOctokitPackage
   <== CreateOctokitReactivePackage

The resulting target order is:
 - SourceLink
 - CreateOctokitPackage
 - CreateOctokitReactivePackage
 - CreatePackages
Starting Target: SourceLink
...
Finished Target: SourceLink
Starting Target: CreateOctokitPackage
...
Finished Target: CreatePackages
...
```

The scripts are now more composition-friendly, not sure how others feel about this granularity though...

**Comment by alfhenrik** [comment]
Looks good, I like it :+1:

**Comment by shiftkey** [comment]
Closing this one out in favour of addressing more concrete issues as they are identified, like:

 - versioning packages from CI for better automation
 - writing up the release documentation
 - probably some other things

**Pull request closed without merging**
