### PR TITLE
(build) Update to Cake 0.36.0

### PR DESCRIPTION
**Pull request by devlead**
* Update to Cake.Frosting 0.36.0

### CODE REVIEW

**Comment by shiftkey** [comment]
@devlead thanks for the speedy PR! We've enabled Dependabot on this repository which runs weekly and should upgrade these dependencies anyway. If a future update gets stuck for something I'm happy to be the first to check at it.

If there's a path forward for us that might make your life easier let me know and I can revisit how we co-ordinate all the tasks that this project needs.

**Comment by devlead** [comment]
Cool,  0.37.0 isn't that far away,  then we'll check if that one gets auto updated.

**Comment by shiftkey** [comment]
release_notes: update build scripts to Cake 0.36

**Comment by shiftkey** [comment]
@devlead I found the problem with why these weren't updating - Dependabot config was only looking at the main projects - and now this is configured and updating the `build/build.csproj` dependencies automatically - #2086 #2087 #2088

**Comment by devlead** [comment]
@shiftkey cool, we'll release Cake.Frosting 0.37.0 hopefully this weekend, so then we'll see if it gets picked up.

**Comment by devlead** [comment]
@shiftkey  [Cake.Frosting/0.37.0](https://www.nuget.org/packages/Cake.Frosting/0.37.0) is now on NuGet so hopefully that gets detected.

**Pull request merged**
