### PR TITLE
Adding in support for enterprise audit logs

### LINKED ISSUE #2701: [FEAT]: Support for the Enterprise Audit Log
### Describe the need

Support is missing for the [Enterprise Audit Log](https://docs.github.com/en/enterprise-cloud@latest/rest/enterprise-admin/audit-log)

### SDK Version

_No response_

### API Version

_No response_

### Relevant log output

_No response_

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### PR DESCRIPTION
**Pull request by gitasaurus**
Resolves #2701 

----

### Before the change?

* [Enterprise Audit Log](https://docs.github.com/en/enterprise-cloud@latest/rest/enterprise-admin/audit-log) support not available

### After the change?

* Support for [Enterprise Audit Log](https://docs.github.com/en/enterprise-cloud@latest/rest/enterprise-admin/audit-log)

### Other information

* 

----

### Pull request checklist
- [x] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been reviewed and added / updated if needed (for bug fixes / features)
- [ ] Added the appropriate label for the given change

### Does this introduce a breaking change?

Please see our docs on [breaking changes](https://github.com/octokit/.github/blob/master/community/breaking_changes.md) to help!

- [ ] Yes (Please add the `Type: Breaking change` label)
- [x] No

If `Yes`, what's the impact:  

* The [ApiConnectionTests+TheGetAllMethod](https://github.com/octokit/octokit.net/blob/a3299ac4b45bed5e12be61376748c1533b4627cd/Octokit.Tests/Http/ApiConnectionTests.cs#L86) is failing.  NSubstitute is returning null ApiInfo from the GetAll initial apiconection call.

### Pull request type

 
 

Please add the corresponding label for change this PR introduces:
- Bugfix: `Type: Bug`
- Feature/model/API additions: `Type: Feature`
- Updates to docs or samples: `Type: Documentation`
- Dependencies/code cleanup: `Type: Maintenance`

----

### CODE REVIEW

**Comment by gitasaurus** [comment]
@kfcampbell , do you have any guidance on fixing [ApiConnectionTests+TheGetAllMethod](https://github.com/octokit/octokit.net/blob/a3299ac4b45bed5e12be61376748c1533b4627cd/Octokit.Tests/Http/ApiConnectionTests.cs#L86)?

**Comment by kfcampbell** [comment]
@gitasaurus I'm currently struggling to reproduce this locally. Running unit tests using `dotnet test` is passing for me on .NET 7.0.102. I'm not sure if it's failing using .NET 5 or .NET 6 during this test, though perhaps we should think about removing .NET 5 testing as it's reached end-of-life.

**Comment by gitasaurus** [comment]
Thanks for looking at this.  I will update this pull request tomorrow.  I found that the paging for Audit Logs does not work the same as the other APIs.  I have added a way to address that.  Please hold off on approving this until then.

**Comment by kfcampbell** [comment]
:+1:, although the build is still failing so I can't approve/merge until that's set.

**Comment by gitasaurus** [comment]
@kfcampbell , fixed the failing tests.

**Review by nickfloyd — APPROVED** [review]
@gitasaurus Thanks for adding this feature here! ❤️

**Pull request merged**
