### PR TITLE
Cleanup obsolete items

### PR DESCRIPTION
**Pull request by M-Zuber**
per #1194 (specifically [this comment](https://github.com/octokit/octokit.net/issues/1194#issuecomment-199810285))

- one small item to draw attention to is [this question](https://github.com/octokit/octokit.net/issues/1194#issuecomment-202014873)

### CODE REVIEW

**Comment by ryangribble** [comment]
> one small item to draw attention to is this question

As per my reply on #1194 I suggest we should just :fire: the `ApiExtensions.GetRedirect()` method

**Comment by M-Zuber** [comment]
@ryangribble done

**Comment by ryangribble** [comment]
Oops, it looks like there is one more reference in `ApiConnection` and `IApiConnection` with `GetRedirect()`

The problem is, the concrete implementation was made obsolete 111 days ago, but the interface member hasnt been marked obsolete at all! :sob: 

But if we have to keep this, then it means we have to keep the `ApiExtension` one around as well, but that seems kinda pointless since the `GetRedirect()` will never actually get a HTTP 302 response anyway and thus will always throw an exception

@shiftkey what do you reckon to :fire:ing [`IApiConnection.GetRedirect()`](https://github.com/octokit/octokit.net/blob/master/Octokit/Http/IApiConnection.cs#L304), eventhough it wasnt marked obsolete?  Note that the concrete implementation, as well as multiple other places regarding Redirects and ArchiveLinks HAVE been obsolete for 100+ days

**Comment by M-Zuber** [comment]
:sob: 
That's what I get for pushing my machines RAM too hard. The error in VS hadn't show up by the time the commit was pushed....

I'll wait for @shiftkey's response (may have to wait until after #build :smile: ) and follow his recommendation

**Comment by shiftkey** [comment]
> what do you reckon to :fire:ing IApiConnection.GetRedirect(), eventhough it wasnt marked obsolete? Note that the concrete implementation, as well as multiple other places regarding Redirects and ArchiveLinks HAVE been obsolete for 100+ days

I'd be breaking my own rule here, and covering over an oversight of mine. Let's add the `[Obsolete]` to the interface and leave it alone for this release.

**Comment by ryangribble** [comment]
so @M-Zuber just chasing up on this one, I take it you are good to rebase to latest master and also tackle the redirect methods according to @shiftkey's comments

**Comment by M-Zuber** [comment]
I'm good to do the work, but on the road ATM. 
Will attempt to get to it in the next day or two

**Comment by M-Zuber** [comment]
@shiftkey @ryangribble rebased and updated code with regards to `.GetRedirect`.
Would love if I could get some :eyes: on the changes to make sure that the changes are correct.

**Comment by shiftkey** [comment]
This all seems good to me. @ryangribble anything else to add here?

**Comment by ryangribble** [comment]
All good!  I love that feeling of cleaning things up :grinning:

**Comment by ryangribble** [comment]
LGTM

**Pull request merged**
