### PR TITLE
Implement user Administrator Client

### PR DESCRIPTION
**Pull request by paladique**
Per, #1030. All implemented tests are passing.

### CODE REVIEW

**Comment by shiftkey** [comment]
@paladique just some xml-docs changes which are making CI cry currently:

```
 1) Building ./Octokit.sln failed with exitcode 1. 
  2) CS1572: Clients\ObservableUserAdministrationClient.cs(17,26): XML comment has a param tag for 'client', but there is no parameter by that name 
  3) CS1573: Clients\ObservableUserAdministrationClient.cs(18,77): Parameter 'userAdministrationClient' has no matching param tag in the XML comment for 'ObservableUserAdministrationClient.ObservableUserAdministrationClient(IUserAdministrationClient)' (but other parameters do)
```

**Comment by Haacked** [comment]
Hmm, looks like `RepositoryPagesClientTests` is failing but that's unrelated to this change. @shiftkey known issue?

**Comment by naveensrinivasan** [comment]
Also the convention test are failing because of observables.

```
The resulting target order is:
 - ConventionTests
Starting Target: ConventionTests 
mono  /Users/naveen/code/octokit.net/tools/xunit.runner.console/tools/xunit.console.exe "/Users/naveen/code/octokit.net/Octokit.Tests.Conventions/bin/Release/Octokit.Tests.Conventions.dll" -parallel none -html "./testresults/xunit.html" 
xUnit.net console test runner (64-bit .NET 4.0.30319.17020)
Copyright (C) 2015 Outercurve Foundation.

Discovering: Octokit.Tests.Conventions
Discovered:  Octokit.Tests.Conventions
Starting:    Octokit.Tests.Conventions
   Octokit.Tests.Conventions.SyncObservableClients.CheckObservableClients(clientInterface: typeof(Octokit.IUsersClient)) [FAIL]
      Octokit.Tests.Conventions.InterfaceMissingMethodsException : Methods not found on interface IObservableUsersClient which are required:
       - get_Administration
      Stack Trace:
         <filename unknown>(0,0): at Octokit.Tests.Conventions.SyncObservableClients.CheckObservableClients (System.Type clientInterface)
            at (wrapper managed-to-native) System.Reflection.MonoMethod:InternalInvoke (System.Reflection.MonoMethod,object,object[],System.Exception&)
         <filename unknown>(0,0): at System.Reflection.MonoMethod.Invoke (System.Object obj, BindingFlags invokeAttr, System.Reflection.Binder binder, System.Object[] parameters, System.Globalization.CultureInfo culture)
Finished:    Octokit.Tests.Conventions

```

**Comment by shiftkey** [comment]
@haacked

> Hmm, looks like RepositoryPagesClientTests is failing but that's unrelated to this change

You're right. This somehow slipped through the initial PR passing CI https://github.com/octokit/octokit.net/pull/1061/files#r50933117 - but the fix 5ca6633cb133ca8db4f2be17c2ebb0e26a446d64 is now in master.

Perhaps this branch was created before, in which case a merge or cherry-pick should pull in the fix...

**Comment by Haacked** [comment]
@paladique you could merge master into your branch and push. Or, if you're feeling adventurous, rebase your branch against master and force push to this branch.

**Comment by shiftkey** [comment]
Great work @paladique, and thanks for the contribution!

**Comment by Haacked** [comment]
thumbs-up-pink-glasses

**Comment by paladique** [comment]
:tada:

**Pull request merged**
