### PR TITLE
Final tidyups for dotnetcore

### PR DESCRIPTION
**Pull request by ryangribble**
- Update contributors docs for dotnetcore/CAKE
- Remove some references to old projects/namespaces
- Get rid of the old `/packages` folder

### CODE REVIEW

**Comment by mderriey** [comment]
Great, I'll take a look at this quickly. Thanks for taking the bite on this one!

**Comment by mderriey** [comment]
@ryangribble That looks great, thanks again. I made a few minor changes, could you please have a look?

**Comment by ryangribble** [comment]
LGTM

**Comment by mderriey** [comment]
Ooh crap I missed this one!! Thank youuuuu

**Pull request merged**
