### PR TITLE
search across multiple repositories

### LINKED ISSUE #834: search across multiple repositories
it's currently impossible to do something like this:

> https://api.github.com/search/issues?q=repo:aspnet/dnx+repo:aspnet/logging+type:pr+state:open&sort=created&order=desc&per_page=100

with Octokit. The syntax is valid, but we constrain things currently to one repository.

cc @damianedwards

### PR DESCRIPTION
**Pull request by shiftkey**
Fixes #834 

This is a breaking API change to support being able to search across repositories. We currently have an `ctor` overload that accepts an `owner` and `name` for the repository:

```csharp
var request = new SearchIssuesRequest("windows", "aspnet", "dnx");
```

The change here is adding a public property `Repos` which accepts a collection of `owner/name` strings (i've added some validation to ensure these are formatted correctly for the server):

```csharp
var request = new SearchIssuesRequest("windows");
request.Repos = new Collection<string> {
    "aspnet/dnx",
    "aspnet/dnvm"
};
```

This replaces the old `Repo` property, which was constrained to one string:

```csharp
var request = new SearchIssuesRequest("windows");
request.Repo = "aspnet/dnx";
```

Rather than carry around both `Repo` and `Repos` for a period of time (leading to possible confusion), I'm just going to :fire: the property here - I think many people would prefer to just use the `Repos` property anyway...

- [x] confirm regex rules match our repository rules
- [x] make changes in `SearchIssueRequest`
- [x] make changes in `SearchCodeRequest`
- [x] a more-friendly abstraction than just a collection?
- [x] document how to search issues (with some examples)
- [x] document how to search pull requests (with some examples)
- ~~[ ] document an example of searching code~~
- [x] wtf ci?

[Rendered docs](https://github.com/octokit/octokit.net/blob/refine-search-api/docs/search.md)

cc @damianedwards @M-Zuber

### CODE REVIEW

**Comment by shiftkey** [comment]
@damianedwards @M-Zuber writing up a walkthrough of the search options available - [how does this read?](https://github.com/octokit/octokit.net/blob/refine-search-api/docs/search.md)

**Comment by M-Zuber** [comment]
It reads quite nicely. 
The examples are very nice to have, a bonus would be a simple run down of the properties available even if they don't have examples.  (I would be willing to try and do a PR once this in)

**Comment by khellang** [comment]
What about creating a specialized object for holding the repos? This way you could use a custom collection initializer, forcing the user to specify both owner and repo name.

**Comment by shiftkey** [comment]
@khellang good point - if I'm breaking the API here I'll see if I can do better than just a collection

**Comment by M-Zuber** [comment]
Preaching to the choir, but I fully agree with @khellang

**Comment by khellang** [comment]
Sent a PR at #842

**Comment by Haacked** [comment]
This is looking pretty good. Anything needing specific review?

**Comment by shiftkey** [comment]
@haacked not really, I should write an example for `SearchCodeRequest.cs` because that's impacted by this change. But I think everything in the code is :sparkles:. I'll add a note.

**Comment by Haacked** [comment]
@shiftkey should I merge this?

**Comment by shiftkey** [comment]
@haacked sure, I just like putting docs in front of me - because otherwise they'll never get written :trolleybus:

**Comment by Haacked** [comment]
:sparkles: all around.

**Pull request merged**
