### PR TITLE
Arbitrarymarkdown

### PR DESCRIPTION
**Pull request by chenjiaming93**
#938
added NewArbitraryMarkdown Class and implemented RenderArbitraryMarkdown method and unit tests.

### CODE REVIEW

**Comment by chenjiaming93** [comment]
My build in visual studio is good. 
I am confused by the BuildApp process. It seems that it will generate 3 new projects called Mono-touch , Netcore 45 and Portable. I'll try to find out those how those files had gone missing.

**Comment by Haacked** [comment]
Hi @chenjiaming93 

You just need to run the following command locally and then commit the changes.

`.\build FixProjects`

It's all described in our [CONTRIBUTING](https://github.com/octokit/octokit.net/blob/master/CONTRIBUTING.md) document.

**Comment by chenjiaming93** [comment]
failed due to #904

**Comment by shiftkey** [comment]
@chenjiaming93 have you committed and pushed the changes to the project file to your branch? I can only see the original error occurring...

**Comment by shiftkey** [comment]
Closing in favour of #947

**Pull request closed without merging**
