### PR TITLE
[Feat] Add Advanced Security Properties to Repository Get/Update

### PR DESCRIPTION
**Pull request by SlyckLizzie**
----

### Before the change?

* Repository get/update did not implement Advanced Security objects

### After the change?

* Repository get/update implements Advanced Security properties

### Pull request checklist
- [ ] Tests for the changes have been added (for bug fixes / features)
- [x] Docs have been reviewed and added / updated if needed (for bug fixes / features)

### Does this introduce a breaking change?

Please see our docs on [breaking changes](https://github.com/octokit/.github/blob/master/community/breaking_changes.md) to help!

- [x] Yes
- [ ] No

----

### CODE REVIEW

**Comment by kfcampbell** [comment]
Do you mind explaining a little more why this is a breaking change? It looks purely additive at the moment.

**Comment by SlyckLizzie** [comment]
For the UpdateRepository method, I am unable to make the SecurityAndAnalysis object nullable because it requires the c# language target to be 8 or higher whereas this project is on 7.3.

**Comment by SlyckLizzie** [comment]
@kfcampbell  - Do you need any additional information for this?

**Comment by SlyckLizzie** [comment]
Accidentally PR'd this from main on my end. Going to re-do it

**Pull request closed without merging**
