### PR TITLE
added support for DateTime serialized as FileTime

### PR DESCRIPTION
**Pull request by itaibh**

### CODE REVIEW

**Comment by shiftkey** [comment]
@itaibh can you provide some more context for this change? Also, this might be worth upstreaming to [SimpleJson](https://github.com/facebook-csharp-sdk/simple-json) if it's useful more broadly...

**Comment by itaibh** [comment]
In some cases GitHub sends wrong date format for the "created_at" and "pushed_at" fields. This is a GitHub bug, probably, but still, such a convention should be supported (and it would have saved me hours of debugging).

Back in 2015 there was an open issue on this, which I commented on today, but I can't find it right now. I'm sending this from my phone, and don't have the full attention to provide more info right now.

**Comment by shiftkey** [comment]
@itaibh thanks for the extra info. I found #825 where you commented earlier.

> This is a GitHub bug, probably, but still, such a convention should be supported (and it would have saved me hours of debugging).

In your other comment you mention this:

> Also, from the timing it seems the problem had returned only recently (about two weeks ago).

If this is a recent regression then I'd love to try and chase this down, because we should be consistent with these fields. If you can point me to a repository which fired a webhook with the wrong format for `created_at` and `pushed_at` in the payload I can chase that up internally and confirm it's been resolved while we discuss this fix.

**Comment by itaibh** [comment]
I'm experimenting with web hooks on my own fork of spoon-knife.
I noticed that it happens for some push events.

**Pull request closed without merging**
