### PR TITLE
Fix assembly versioning/properties and handle platform exception

### PR DESCRIPTION
**Pull request by ryangribble**
Thanks to @mderriey for pointing out that the Assembly/File versions are not being set automatically during the build process due to us still having `SolutionInfo.cs` and `AssemblyInfo.cs` files with hardcoded version numbers 🤦‍♂️ 

This PR gets rid of Solution/AssemblyInfo properties in favour of setting everything via the csproj, including some more of the nuget package metadata.  Our existing CAKE build already specifies the GitVersion calculated version string via the `dotnet build` task, so this should now flow through to AssemblyVersion, FileVersion, AssemlbyInformationalVersion attributes.  Similarly the nuget package metadata should be handled by the `dotnet pack` task.  I'll check out the AppVeyor build artifacts to confirm...

Also took the opportunity to tweak the user agent string we calculate, to include the informational version (so we get pre release tags if any are set) rather than assembly version (which can only be numeric and doesn't include pre release tags), and added an attempted fix for #1617 by catching any exceptions when determining the platform OS/architecture

### CODE REVIEW

**Comment by ryangribble** [comment]
Downloading the artifacts from AppVeyor, things are looking pretty :gem:

Nuget package info/version is ✅ 
Assembly/File Version is numeric 0.27.0 ✅ 
Product version includes the pre-release version (in this case, `-PullRequest1660`) ✅ 

image

**Comment by ryangribble** [comment]
release_notes: Corrected assembly versioning during build process and allow Octokit to run in environments where `PlatformNotSupported` exception is encountered when initializing the API connection (eg AWS Lambda)

**Comment by ryangribble** [comment]
@mderriey can you take a 👀 and let me know what you think?

**Comment by mderriey** [comment]
It looks fantastic!

One thing I noticed is that in the NuGet Package Explorer screenshot for the `Octokit.Reactive` package, the dependency on `Octokit` mentions the default `0.0.0-dev` version even though it looks these packages have been produced by the Cake build since the package itself has the correct version calculated by GitVersion. That seems a bit strange...

Also, if I had to nitpick, I'd say _dotnetcore_ in the description reads funny to me and if I was a consumer of the package, it'd make more sense for me to read _.NET Core_ or _.NET Standard_.

**Comment by ryangribble** [comment]
Fixed up the wording.

The version dependency of Octokit.Reactive on Octokit is annoying... things were looking so nice and straight forward!  We will have to dig into this

**Comment by mderriey** [comment]
How good would it be if that fixed it!

**Comment by ryangribble** [comment]
OK sounds like for the time being we need to use a workaround of specifying the version on the dotnet restore.  This is because the `\Octokit.Reactive\obj\project.assets.json` file is used for the `dotnet pack` version dependency stuff, and it's contents are set at `dotnet restore` time. 
https://github.com/NuGet/Home/issues/4337

Testing locally looks good, let's see what ApVeyor spits out

**Comment by mderriey** [comment]
Blinging 💯! 

image

**Comment by ryangribble** [comment]
image

**Comment by mderriey** [comment]
Thanks for the wording change.

Also, kudos for the GitHub-fu!

:shipit:

**Comment by ryangribble** [comment]
release_notes: Octokit can now run in environments where `PlatformNotSupported` exception was encountered when initializing the API connection (eg AWS Lambda)

**Pull request merged**
