### PR TITLE
Add Waiting to WorkflowJobStatus

### LINKED ISSUE #2730: [BUG]: There's no WorkflowJobStatus.Waiting
### What happened?

While querying for the workflow job status, suddenly it returns sth other than `queued` `in_progress` nor `completed` but `waiting`.
As it's waiting for some prod approval.

### Versions

octoket v6.1.0

### Relevant log output

_No response_

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### PR DESCRIPTION
**Pull request by vuryleo**
Resolves #2730 

----

### Before the change?

* 

### After the change?

* 

### Other information

* 

----

### Pull request checklist
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been reviewed and added / updated if needed (for bug fixes / features)
- [ ] Added the appropriate label for the given change

### Does this introduce a breaking change?

Please see our docs on [breaking changes](https://github.com/octokit/.github/blob/master/community/breaking_changes.md) to help!

- [ ] Yes (Please add the `Type: Breaking change` label)
- [X] No

If `Yes`, what's the impact:  

* N/A

### Pull request type

 
 

Please add the corresponding label for change this PR introduces:
- Bugfix: `Type: Bug`
- Feature/model/API additions: `Type: Feature`
- Updates to docs or samples: `Type: Documentation`
- Dependencies/code cleanup: `Type: Maintenance`

----

### CODE REVIEW

**Comment by kfcampbell** [comment]
Can you share a request that produces the error this PR fixes? Have you tested this with a request that returns a WorkflowJobStatus and validated serialization/deserialization works?

**Comment by vuryleo** [comment]
```bash
$ curl -H "Authorization: Bearer GITHUB_ACCESS_TOKEN" 'https://[redacted]/api/v3/repos/[redacted]/[redacted]/actions/jobs/[redacted]'  | jq .
```
```json
{
  "id": [redacted],
  "run_id": [redacted],
  "run_url": "https://[redacted]/api/v3/repos/[redacted]/[redacted]/actions/runs/[redacted]",
  "run_attempt": 1,
  "node_id": "[redacted]",
  "head_sha": "[redacted]",
  "url": "https://[redacted]/api/v3/repos/[redacted]/[redacted]/actions/jobs/[redacted]",
  "html_url": "https://[redacted]/[redacted]/[redacted]/runs/[redacted]?check_suite_focus=true",
  "status": "waiting",
  "conclusion": null,
  "started_at": "2023-06-28T23:03:53Z",
  "completed_at": null,
  "name": "[redacted]",
  "steps": [],
  "check_run_url": "https://[redacted]/api/v3/repos/[redacted]/[redacted]/check-runs/[redacted]",
  "labels": [
    "[redacted]"
  ],
  "runner_id": null,
  "runner_name": null,
  "runner_group_id": null,
  "runner_group_name": null
}
```

**Comment by vuryleo** [comment]
```csharp
new GitHubClient(new ProductHeaderValue("ph")).Actions.Workflows.Jobs.Get(OrganizationName, RepositoryName, Id)
```
throws
```csharp
Newtonsoft.Json.JsonSerializationException
```

**Review by kfcampbell — APPROVED** [review]
I'm unable to find a reproducible case for this. Please report back if this solves your issue or additional work is needed!

**Pull request merged**
