### PR TITLE
Add Milestone property to PullRequest

### LINKED ISSUE #1071: PullRequest missing Milestone property
Related: https://github.com/octokit/octokit.net/issues/910

### PR DESCRIPTION
**Pull request by Eilon**
Fixes #1071

### CODE REVIEW

**Comment by Haacked** [comment]
Thanks! :sparkles:

**Comment by Eilon** [comment]
Thanks dude! Now looking forward to the next release of Octokit :smile:

**Comment by Haacked** [comment]
We should try and get something out soonish. :smile:

**Comment by Eilon** [comment]
Cool.

**Comment by shiftkey** [comment]
@Haacked @eilon on my list for this week, hopefully tomorrow

**Pull request merged**
