### PR TITLE
Consolidate committer info

### PR DESCRIPTION
**Pull request by Haacked**
Replace `SignatureResponse` and `CommitEntity` with `Committer`

A recent PR added `CommitEntity` but we already had `SignatureResponse` expressly for this purpose.

So this commit renames `SignatureResponse` to `Committer` and removes `CommitEntity` and replaces it with `Committer`.

I also had to retarget the NetCore45 app so it builds in VS 2015.

### CODE REVIEW

**Comment by bslliw** [comment]
My bad, didn't know about this one. But why was GitHubCommit changed back to use Author instead of Committer? (that was the initial issue)

**Comment by willsb** [comment]
My bad, didn't know about this one. But why was GitHubCommit changed back to use Author instead of Committer? (that was the initial issue)

**Comment by Haacked** [comment]
> My bad, didn't know about this one. But why was `GitHubCommit` changed back to use `Author` instead of `Committer`? (that was the initial issue)

Because according [to the docs here](https://developer.github.com/v3/repos/commits/#get-a-single-commit), the `author` and `committer` for a `GitHubCommit` correspond to a GitHub account (aka `Author`).

The `commit` property of `GitHubCommit` also has `author` and `committer` but those correspond to `Committer`.

I think the confusion stems from the fact that the API returns GitHub objects as well as Git objects and Octokit.net has confused the two in some places.

A `Committer` is the minimal signature that a Git commit contains `{'name', 'email', 'date'}`. GitHub will try to associate a committer (and author) of a Git commit to a GitHub account. It can't always do that and now that I think about it, I'm not sure what it responds when it can't.

**Comment by Haacked** [comment]
I commented on [the original issue](https://github.com/octokit/octokit.net/issues/779#issuecomment-143803506)

**Pull request merged**
