### PR TITLE
Release v0.24 - A Sight For Sore Eyes

### PR DESCRIPTION
**Pull request by ryangribble**
This is the first release where I'm putting it together!  Here is the checklist I'm going to work through.

Aiming to release on the 17th January

- [x] check for any last minute PR's that can make it in
- [x] initial release notes
- [x] version bump
- [x] run `build FormatCode` to tidy up whitespace/formatting
- [x] integration tests all pass
- [x] tweak release notes to call out any breaking changes/special instructions (such as the multiple assignees implications on `NewIssue` and `IssueUpdate`
- [x] :thumbsup: from @shiftkey or @Haacked
- [x] :thumbsup: from key contributors @maddin2016 @M-Zuber etc
- [ ] tag and publish to NuGet
- [ ] :shipit:

### CODE REVIEW

**Comment by M-Zuber** [comment]
Looks good to me!
I will try and get #1523 up to snuff to try and squeeze it into this release.

**Comment by ryangribble** [comment]
Ive fixed a good handful of integration tests, some of them were really quite strange (like `AccountType.Bot` now being a thing!).

All integration tests are now passing!

**Comment by M-Zuber** [comment]
oo.. that is probably related to [Integrations](https://developer.github.com/early-access/integrations/)

**Comment by ryangribble** [comment]
OK I think this is good to go, just waiting for an 👀 from @shiftkey or @Haacked

**Comment by mderriey** [comment]
Exciting! Great work @ryangribble 👍

**Comment by ryangribble** [comment]
Well, here goes nothing!

**Comment by ryangribble** [comment]
Published:

https://www.nuget.org/packages/Octokit/0.24.0
https://www.nuget.org/packages/Octokit.Reactive/0.24.0

**Comment by maddin2016** [comment]
:tada 👍

**Pull request merged**
