### PR TITLE
[WIP] Documentation Is A Nice Thing To Have™

### LINKED ISSUE #463: I'd really appreciate some documentation
Hello, i know that it's hard to create a full documentation of library, but come on, one small example? Really? I'm sorry, but this library is kinda useless without proper documentation, so pelase, anybody, do it...

### PR DESCRIPTION
**Pull request by shiftkey**
This will be the feature branch for whatever documentation we think needs to live in Octokit.

Currently we're just pulling in everything under the `docs` folder, but I'm sure you all have ideas or suggestions.

You can view the current state of this branch here: https://octokitnet.readthedocs.org/en/documentation/

Fixes #463

### CODE REVIEW

**Comment by shiftkey** [comment]
Just organized the existing documentation under something resembling a hierarchy:

screen shot 2015-10-28 at 7 51 22 pm

I'm sure there's stuff you'd like to see in here - sound off!

**Comment by hahmed** [comment]
:+1: 

Looks really good, love the way this is shaping out to be.

**Comment by shiftkey** [comment]
After getting a good(-ish) night's sleep I think there's a few sections we can define here:

 - **Introduction** - walk through the basics of using Octokit in your app
 - **Features** - explain the various parts of the API with some sample code
 - **Guides** - more complex examples and scenarios
 - **Internals** - discussions about the architecture and how it all works
 - **Contributing** - things current and potential contributors should read

**Comment by alfhenrik** [comment]
This is looking awesome! :+1:

**Comment by shiftkey** [comment]
Once this goes green, I'll merge it and try splitting out some documentation tasks if people want to dive into this.

**Pull request merged**
