### PR TITLE
Add basic codespaces api

### LINKED ISSUE #2721: [FEAT]: Support Codespace APIs
### Describe the need

Octokit.net should support the codespace apis to query and manage codespaces for a user, repo, etc.

### SDK Version

_No response_

### API Version

_No response_

### Relevant log output

_No response_

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### PR DESCRIPTION
**Pull request by asklar**
Resolves #2721 

----

### Before the change?

* no codespaces api :)

### After the change?

* adds basic Codespaces API:
  * GetAll()
  * Get(name)
  * GetForRepository(owner, repo)
  * Start(name)
  * Stop(name)

### Other information

----

### Pull request checklist
- [X] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been reviewed and added / updated if needed (for bug fixes / features)
- [ ] Added the appropriate label for the given change

### Does this introduce a breaking change?

Please see our docs on [breaking changes](https://github.com/octokit/.github/blob/master/community/breaking_changes.md) to help!

- [ ] Yes (Please add the `Type: Breaking change` label)
- [X] No

If `Yes`, what's the impact:  

* N/A

### Pull request type

 
 

Please add the corresponding label for change this PR introduces:
- Bugfix: `Type: Bug`
- Feature/model/API additions: `Type: Feature`
- Updates to docs or samples: `Type: Documentation`
- Dependencies/code cleanup: `Type: Maintenance`

----

### CODE REVIEW

**Comment by asklar** [comment]
@kfcampbell @nickfloyd could you folks take a look? Thanks!

**Comment by kfcampbell** [comment]
@asklar I've approved the Actions workflow, which should get you some information about the test error.

**Comment by asklar** [comment]
thanks @kfcampbell ! I had forgotten to make the client type public :) (it was marked internal)
Could you kick the pipeline again?

**Comment by asklar** [comment]
it's failing because the Observable client doesn't expose these. @kfcampbell  Is there a way to say "sorry, not supported at the moment through the reactive wrapper, use the other one"?

**Comment by asklar** [comment]
pushed an empty IObservableCodespacesClient, hopefully this works now : )

**Comment by asklar** [comment]
conventions tests was failing, I've fixed it now. Sorry for the back and forth :) @kfcampbell

**Comment by asklar** [comment]
another one

**Comment by asklar** [comment]
@kfcampbell @nickfloyd sorry to bug you, could you kick the ci?

**Review by nickfloyd — APPROVED** [review]
Thanks for doing this @asklar! ❤️  LGTM!

**Pull request merged**
