### PR TITLE
Deployment and DeploymentStatus API enhancements preview period. (#1249)

### PR DESCRIPTION
**Pull request by ErikSchierboom**
This PR implements the functionality described in issue #1249, which is to add new preview fields.

I was looking into adding tests for these methods, but how would I do that? If I look at the [deployments API](https://developer.github.com/v3/repos/deployments/#create-a-deployment), the response does not contain any of the new information. Is that correct?

### CODE REVIEW

**Comment by ryangribble** [comment]
> If I look at the deployments API, the response does not contain any of the new information. Is that correct?

Try changing the `GetAll` methods to also include the new preview Accepts header, it could be the documentation wasn't updated fully because normally the extra information is also returned in payloads when specifying the preview header

**Comment by ErikSchierboom** [comment]
@ryangribble Should I also be adding the fields added to the `NewDeployment` and `NewDeploymentStatus` clases to the `Deployment` and `DeploymentStatus` classes? I do get returned values for these new fields in the HTTP response, so I could map them.

**Comment by ryangribble** [comment]
Yep! Sounds good

**Comment by ErikSchierboom** [comment]
@ryangribble I've updated the PR with some tests.

**Comment by ryangribble** [comment]
@ErikSchierboom it's looking pretty good :grinning:  There are a couple of failed convention tests if you check the build results, due to mutable properties (a couple of fields you added have a public setter rather than protected) which need to be tidied up.

And other than that, it'd be really awesome to see the existing integration tests for [Depoloyments](https://github.com/octokit/octokit.net/blob/master/Octokit.Tests.Integration/Clients/DeploymentsClientTests.cs) and [DeploymentStatus](https://github.com/octokit/octokit.net/blob/master/Octokit.Tests.Integration/Clients/DeploymentStatusClientTests.cs) updated/added to ensure these new fields are functioning correctly against the real github API.  If you havent already set yourself up for integration tests, check the details in the [CONTRIBUTING](https://github.com/octokit/octokit.net/blob/master/CONTRIBUTING.md#slow-tests) guide (namely, create a separate test account on github.com so you don't impact your real account, and use the provided powershell script to configure your integration test settings).

Looks like there are already a range of integration tests so it could just be as simple as enhancing some of them to assert that key fields are actually populated rather than just `Assert.NotNull(deployment)` and so on

**Comment by ErikSchierboom** [comment]
I'll get on it!

**Comment by ErikSchierboom** [comment]
@ryangribble The builds are now successful :) I have also added integration tests for the newly added properties, except for the `AutoInactive` property which isn't returned by the API.

**Comment by ryangribble** [comment]
> except for the AutoInactive property which isn't returned by the API.

Just to clarify this statement - are you saying this is an issue, or just meaning that it isnt meant to be returned (since it sounds like it''s more a field on the update request, not on an actual deployment or DeploymentStatus itself?)

**Comment by ErikSchierboom** [comment]
@ryangribble As far as I can tell, it makes sense to not return that field as it appears to be intended for use only when creating/updating.

**Comment by ryangribble** [comment]
Yep agreed, just wanted to clarify you meant that too :)

Ive done a final review and also pulled your branch and run the integration tests etc... 
This is :gem: and ready to go... congratulations on your first octokit contribution!

**Comment by ryangribble** [comment]
LGTM

**Comment by ErikSchierboom** [comment]
Great! Thanks for the help.

Hurray

**Pull request merged**
