### PR TITLE
Implement Check Suites API

### PR DESCRIPTION
**Pull request by ryangribble**
Split out of #1801 to focus on Check Suites first

Remaining things to do:
- [x] XmlDoc for Response objects
- [x] XmlDoc for Observable client/interface
- [x] Tests for Observable client methods
- [x] Observable implementations

### CODE REVIEW

**Comment by ryangribble** [comment]
@Cyberboss @StanleyGoldman do you reckon you could take a look before I hit the button?

**Comment by StanleyGoldman** [comment]
For sure, I was playing with the branch a few days ago.
Will update today.

**Comment by StanleyGoldman** [comment]
I also just realized I was playing with `check-runs` which is based on this.
I have a few comments there for when you create that pull request.

**Comment by ryangribble** [comment]
Yeah check suite's by themself are fairly useless, I'll merge this PR soon and then rebase the check-runs branch and create that PR

I just realised I missed some integration tests for the repositoryId versions of all the methods for check suites, so I'll add those first then merge

**Comment by ryangribble** [comment]
release_notes: Implemented Check Suites component of [New Checks Api (Public Beta)](https://developer.github.com/changes/2018-05-07-new-checks-api-public-beta/)

**Pull request merged**
