### PR TITLE
Added get release by tag endpoint

### PR DESCRIPTION
**Pull request by tasadar2**
This adds the endpoint to retrieve a release by owner, repo, and tag. [https://developer.github.com/v3/repos/releases/#get-a-release-by-tag-name](https://developer.github.com/v3/repos/releases/#get-a-release-by-tag-name)

### CODE REVIEW

**Comment by tasadar2** [comment]
Looks like the linux build failed while installing .NET, though I am not familiar enough with travis to know if that is fixable in code or not.

**Comment by shiftkey** [comment]
> Looks like the linux build failed while installing .NET, though I am not familiar enough with travis to know if that is fixable in code or not.

I don't believe this issue is related to your contribution. I've restarted the build to see if it's repeatable (and thus probably an infrastructure issue).

**Comment by ryangribble** [comment]
Yeah it was a travis issue

This looks good @tasadar2, are we able to add an integration test as well?

**Comment by tasadar2** [comment]
I added some integration tests.

**Comment by ryangribble** [comment]
thanks @tasadar2 !

I pushed some tidy ups to the integration tests.

I also added the implementation for `repositoryId` as well (all API calls that use `owner/repo` also have a corresponding endpoint that takes the `repositoryId` instead).

Do you mind reviewing the changes I made and let me know if you are good for this to be merged?  🙏

**Comment by ryangribble** [comment]
Thanks @tasadar2 and congrats on your first contribution!

LGTM

**Pull request merged**
