### PR TITLE
Implement the Meta endpoint

### PR DESCRIPTION
**Pull request by Haacked**
See https://developer.github.com/v3/meta/ for more information about
this endpoint.

### CODE REVIEW

**Comment by Haacked** [comment]
Hey @naveensrinivasan do you happen to have time to review this PR for me?

**Comment by naveensrinivasan** [comment]
@Haacked I'll do that.

**Comment by naveensrinivasan** [comment]
Looks good to me  :+1:

**Comment by Haacked** [comment]
Thanks!

**Comment by Haacked** [comment]
This is now [live on NuGet](https://www.nuget.org/packages/octokit) as of version `0.16.0`!

**Pull request merged**
