### PR TITLE
Add Swift language

### PR DESCRIPTION
**Pull request by p-brito**

### CODE REVIEW

**Comment by p-brito** [comment]
@shiftkey can you review pls!?

**Comment by jpam87** [comment]
@shiftkey  pls do, I want that 2

**Comment by p-brito** [comment]
@haacked @alexander-efremov

**Comment by p-brito** [comment]
#2341

**Comment by p-brito** [comment]
@ryangribble @hahmed  @hnrkndrssn anyone?

**Comment by p-brito** [comment]
@alanjrogers

**Comment by khellang** [comment]
https://www.igvita.com/2011/12/19/dont-push-your-pull-requests/

**Comment by p-brito** [comment]
@khellang If nobody solves the issues what do you expect? Of course, people will open PR's :) If octokit does return Language Swift when you search for repositories why doesn't this allow you to search by it?! I understand what you sent, but we are talking about an enum value that probably someone forgot to add. Also, from what I can see the repository is not updated in months. How long it will take to create a patch to solve bugs? Bugs can be solved and the community doesn't need to wait for major or minor versions. https://semver.org

**Comment by khellang** [comment]
Of course it's OK to send PRs with missing enum values, but tagging 4 people on the issue and 7 people on the PR would be considered nagging (by me) and isn't really helpful.

The maintainers of this library has other things to do in their lives than merging your PRs. Please respect that 😅

**Comment by p-brito** [comment]
@khellang if no one answers it's normal that I tag people. If you open an issue to a repo where I am, I will answer you. Ofc, everyone has other things to do :) But that is the responsibility when you have a solution that is advertised and recommended by GitHub to interact with the API.  I hope that these problems are addressed in a patch one day. Have a great day! Ty for answering!

**Review by shiftkey — APPROVED** [review]

**Comment by nickfloyd** [comment]
release_notes: Adds `Swift` to the language type enum so that it can be used when searching for repositories

**Pull request merged**
