### PR TITLE
v0.18 - Bringing The Thunder

### PR DESCRIPTION
**Pull request by shiftkey**
- [x] write up release notes
- [x] verify LINQPad samples are accurate against what's currently in `master`
- [x] integration tests pass - subject to #1079 being merged
- [x] review release notes, add #1079 to breaking changes
- [x] package up
- [x] tag the release
- [x] :shipit:

### CODE REVIEW

**Comment by shiftkey** [comment]
Have dropped the [WIP] tag and am running the tests once more. Planning to publish this tomorrow morning AEDST, so going to let it sit overnight for others to look over...

**Comment by ryangribble** [comment]
didnt want to include #1073 ?  :laughing:

**Comment by shiftkey** [comment]
@ryangribble there's already a lot to go out here :grin: but I'll try and get into the rhythm of more regular releases now the audit stuff is under control...

**Comment by shiftkey** [comment]
:ship:ed - see https://www.nuget.org/packages/Octokit/0.18.0 and  https://www.nuget.org/packages/Octokit.Reactive/0.18.0

**Pull request merged**
