### PR TITLE
Fixed a bug that content cannot be retrieved if "#" is included in a file or folder name. 

### PR DESCRIPTION
**Pull request by minoura-a**
I have confirmed that content can be retrieved even if "#" is included in the file or folder name.
I have confirmed that all unit tests passed.
#2587

### CODE REVIEW

**Comment by kfcampbell** [comment]
@minoura-a nice work! Would you mind adding tests for the new helper you created to match those [here](https://github.com/octokit/octokit.net/blob/main/Octokit.Tests/Helpers/StringExtensionsTests.cs#L68)?

**Comment by minoura-a** [comment]
@kfcampbell 
Thank you for confirming this.
I will create a test, please wait a couple of days.

**Comment by minoura-a** [comment]
@kfcampbell 
Since the EncodeSharp method is only used within the StringExtensions class, I have changed the accessibility of the method to private.
[This](https://github.com/minoura-a/octokit.net/commit/b22bd13a51de02789226a7062b8fc248921d8998) is Comimt.
For this reason, I do not think testing is necessary.
Is this correct?

**Comment by kfcampbell** [comment]
I think it's still worthwhile to create a test for this behavior, similar to the one for `EscapeDoubleQuotes`.

**Comment by minoura-a** [comment]
@kfcampbell 
I have created a test. Could you confirm it?
[This](https://github.com/octokit/octokit.net/blob/8c2c199e058f193fa12ecfba85d3a1aff3c34476/Octokit.Tests/Helpers/StringExtensionsTests.cs#L93) is a commit.

**Comment by minoura-a** [comment]
@kfcampbell 
I seem to be failing the Sourcelink test, is there anything I should do?

**Review by nickfloyd — APPROVED** [review]

**Pull request merged**
