### PR TITLE
Delete the missing files from the csproj for Octokit-Monotouch

### PR DESCRIPTION
**Pull request by thedillonb**
Octokit-Monotouch won't build with the missing files

### CODE REVIEW

**Comment by thedillonb** [comment]
With the portable version out, is there even a need for the Monotouch/Monoandroid versions? Attempting to track down my issue with the `Invalid Format` exception I accidently opened the `XamarinStudio` solution. But I'm not sure that it's even needed anymore?

**Comment by shiftkey** [comment]
@thedillonb It's been a while since I opened Xamarin Studio (expired subscriptions also don't help), so I'm not quite sure whether I can/should drop it.

**Comment by Haacked** [comment]
God I would love it if we could drop it. I am not set up to test it and it would be one lest thing to worry about. @thedillonb At this point, I'm ready to trust your call on this. I assume you've tested it out a bit?

**Comment by shiftkey** [comment]
I'm happy to accept this PR, but I'll also open a discussion about whether we need to support separate MonoTouch/MonoDroid projects these days...

**Comment by shiftkey** [comment]
> God I would love it if we could drop it. 

https://github.com/octokit/octokit.net/issues/719

**Pull request merged**
