### PR TITLE
Rewrite LINQPad samples checks in F#

### PR DESCRIPTION
**Pull request by mderriey**
This is my very first experience with F#.

Feel free to point anything that could be done in an easier/cleaner/more efficient way.

### CODE REVIEW

**Comment by ryangribble** [comment]
So I can't comment on the fsharp code itself but from an operational sense it appears this task runs and suceeds so thats good!

image

A couple of comments
- It might be nice to output the real name of the linqpad sample file somewhere in that build log as the actual task only mentions the temporary file obviously (or perhaps we could make the temporary filenames consist of a randomly generated portion followed by the actual filename like `123abc-1-introducing-octokit.linq`, `123abc-2-releases.linq` etc)

- Would be nice to see what does a build failure look like - eg do we see enough info in the output to know what sample was wrong etc?

- On this PR you should be able to remove any old code (that skipped test etc) that wont be needed anymore

**Comment by mderriey** [comment]
Thanks for the input!
Last commits output the original name of the sample before running it through LINQPad and remove the C# test.

Regarding the issue ID in the PR description, sorry about that, I'm still struggling with this notion. I thought it was meant to be in a commit message. I'm not sure I can update the PR description now - clicking the Edit button allows me to update the title but now the description

**Comment by ryangribble** [comment]
> Regarding the issue ID in the PR description, sorry about that, I'm still struggling with this notion. I thought it was meant to be in a commit message. I'm not sure I can update the PR description now - clicking the Edit button allows me to update the title but now the description

Ah my apologies, I didnt see it in the commit.  That should also close the issue.  Personally i prefer to put it in the PR as people may not read the commit comments but it's all good.  PS you can edit the PR body/1st comment with the pencil icon (as opposed to the edit button which is the title and base branch)

**Comment by ryangribble** [comment]
@shiftkey did you want to look over the F# code or you happy to merge this based on the fact the tests do run?

**Comment by shiftkey** [comment]
@ryangribble code looks good, and AppVeyor is running these on PRs now so I'm 👍 to merging

@mderriey fantastic stuff, thanks for jumping on this!

**Pull request merged**
